### ISSUE TITLE
New AudioEngine class can't play large OGG files

### ISSUE THREAD

**Issue by mixogames** [cocos2d/cocos2d-x#10482]
Hi,

I have tried to play longer OGG files by new AudioEngine::play2D() but it doesn't work at all. I tried several longer OGG files (>2MB).  I debugged the audio engine and the problem seems to be in AudioCache.cpp, if the sound PCM size is larger than PCMDATA_CACHEMAXSIZE.  The loading / queing thread is not calling this method again or something....
I detected this problem on Windows 8, in the latest Cocos2dx 3.4, and tested it in cpp-tests too (in class LargeAudioFileTest).

Thanks,
Attila

**Comment by mixogames** [comment]
I forgot that i detected this problem on win32 device, in latest Cocos2dx 3.4

**Comment by Dhilan007** [comment]
Fixed at https://github.com/cocos2d/cocos2d-x/pull/10498

**Comment by mixogames** [comment]
Thanks for fast response! 

I tried the fix but it still doesn't work well on long OGG files. Now I can hear a half second (or maybe less) part of the music from its begining.  I tested it with 2-3 ogg music files (all were bigger than 3MB).

**Comment by walzer** [comment]
Duplicated with #10498. Let's discuss there.

**Comment by WenhaiLin** [comment]
Fixed at https://github.com/cocos2d/cocos2d-x/pull/11918

**Comment by Sheado** [comment]
Hi All, 

I just tested with a 5mb OGG file on Windows 10 and this issue still happens regularly. I tested in v3.12 as well as latest from git (v3) as of today (7/8/2016). I need this fixed before I can ship my game, and would love to help, but so far I'm not what the cause of the bug is other than it's related to streaming audio. I'm wondering if it's related in any way to: https://github.com/cocos2d/cocos2d-x/issues/14212

**Comment by dumganhar** [comment]
@Sheado, thanks for your feedback, please upload the ogg file then I could test it.

**Comment by dumganhar** [comment]
@Sheado , I reproduced this issue and gonna find the reason.

**Comment by dumganhar** [comment]
@Sheado , it was fixed at https://github.com/cocos2d/cocos2d-x/pull/16303.
Please test and give us feedback. Thanks.

**Comment by Sheado** [comment]
Sorry for the delayed response,
Thanks for taking a look at this @dumganhar 
I'll report back if I find any further issues.

**Comment by dumganhar** [comment]
@Sheado , Thank you. Please notice that, I sent this patch to v3.13 branch. :)
