### ISSUE TITLE
NewAudioEngine bug after incoming call

### ISSUE THREAD

**Issue by davidejones88** [cocos2d/cocos2d-x#10965]
version: 3.3 
platform: iPad Mini 
issue & reproduce: while the game is running if you receive a phone call and close it, when the game opens again, there is no audio at all. I think it is similar to "NewAudioEngine bug. #10381" but even with the proposed fix "Fixed at #10440" I'm still able to reproduce the issue

**Comment by davidejones88** [comment]
Update:
- xCode 6.2, iOS 7/8, cocos2dx-3.4, iPhone/iPad alike
- test-cpp with new audio engine does not play sound when coming back from siri/incoming call
- github fix fixes the siri problem (https://github.com/cocos2d/cocos2d-x/issues/10381)
- this page fix fixes the incoming call problem for iPad (http://discuss.cocos2d-x.org/t/cocos2d-x-3-4-bug-audioengine-3-4-freeze-incoming-call/20547/7)

The only difference is that now it seems that if you manually 'mute' the device with the hardware button, the audio still plays, and you have to turn down the volume if you want to really mute it.

Can someone please confirm all of this? 

Waiting for new cocos2dx release to see how things will work. For the time being it looks like everything is fine.

**Comment by WenhaiLin** [comment]
Fixed at https://github.com/cocos2d/cocos2d-x/pull/12106

**Comment by milos1290** [comment]
This issue still happens on v3.8rc0

How to reproduce:
Open the game on iOS and receive call, make sure it lasts at least 30seconds. Also make sure you have some effects playing not only background music

bool cocos2d::experimental::AudioEngineImpl::resume(int): audio id = 6, error = a003
bool cocos2d::experimental::AudioPlayer::play2d(cocos2d::experimental::AudioCache *):alSourcePlay error code:a003

This happens when coming back to game after call is finished. Any sound after that will not be played.

**Comment by pandamicro** [comment]
@WenhaiLin Please take a look

**Comment by WenhaiLin** [comment]
@milos1290 I fixed it at https://github.com/cocos2d/cocos2d-x/pull/13706

**Comment by milos1290** [comment]
I'll test it today and post results here. I've also noticed that this couldn't be reproduce every time. Sometimes audio will be totally bugged, and no sound will be played,  force close of the game will restore it back, sometimes it will resume normally.

**Comment by WenhaiLin** [comment]
@milos1290 What are the test results?

**Comment by milos1290** [comment]
Sorry for a late reply.

Anyway i've tested it with this fix and i couldn't reproduce it anymore. It seems that everything is working normally after resuming the game from call. I'll post here if i notice anything else.

**Comment by pandamicro** [comment]
Thanks, please comment if you find other issues

**Comment by umair6** [comment]
I am still able to reproduce this issue. If you do not pick the call and calling person drops it, then when you get back to your game all current sounds get stopped.

**Comment by fuyifan** [comment]
@umair6  do you use SimpleAudioEngine somewhere in your project, please check. You can simply add breakpoint at the init function of SimpleAudioEngine

**Comment by umair6** [comment]
@fuyifan  No, I dont use SimpleAudioEngine in my project. I double checked by putting breakpoint. It is not getting called from any where.

**Comment by fuyifan** [comment]
@umair6 add breakpoint on all alcMakeContextCurrent to see whether the context is set wrong value or not called when you get your game back
