### ISSUE TITLE
Label createWithTTF and enableShadow return errors in cocos2dx 3.6

### ISSUE THREAD

**Issue by dariodepaolis** [cocos2d/cocos2d-x#11742]
Just updated to cocos2dx v3.6, my previous working code returns now errors.
I've seen that Label TTF and shadow is the cause, you can simply test with this:

```
auto title = Label::createWithTTF("My Label Text", "myfont.ttf", 40);
title->enableShadow();
addChild(title);
```

This return:

**OpenGL error 0x0502 in ..\renderer\CCTextureAtlas.cpp cocos2d::TextureAtlas::drawNumberOfQuads 691**

If I remove Shadow it's ok, in 3.4 was ok.
However the TTF is displayed correctly, but the debug.log grows with this error repeated continuosly.

Also change params in enableShadow doesn't change the error.
If I use Label createWithSystemFont it's ok.
Tried also with various TTF, same error.

**Comment by dariodepaolis** [comment]
Sorry I've seen now that it was fixed here: https://github.com/WenhaiLin/cocos2d-x/commit/8f6277c5403e46ccde803c3f5e7fae79dbd0050f

I think it's the same issue, so I close myself this issue

**Comment by jyoxun** [comment]
Thank you! It's worked.

**Comment by deathemperor** [comment]
This issue still exists on Android

**Comment by gestern** [comment]
This issue still exist on iOS in cocos2d-x 3.10

**Comment by larsven** [comment]
We are seeing this in 3.10 too. Often together with unreadable text or missing shadows.

Only on Android.

**Comment by dariodepaolis** [comment]
So it's not fixed?

**Comment by larsven** [comment]
In our case it was caused by a sdkbox callback sent on a different thread than we expected.

**Comment by Longpc** [comment]
For me. I got black screen when use admob video reward that have callback is show confirm dialog. But dialog is Black with same error. (Dialog was created from Node, LayerColor and Sprite like background image). Hope that was fixed soon

**Comment by pccsoares** [comment]
issue is back on 3.16
very rarely, labels disappear and console goes crazy looping this message:

OpenGL error 0x0502 in ..\renderer\CCTextureAtlas.cpp cocos2d::TextureAtlas::drawNumberOfQuads 691

And I'm not using shadow on the label that caused the issue.
But I'm also using the createWithTTF

Do we have any workaround for this?

**Comment by MrCapone** [comment]
I've got this error when trying create Label from another thread. Check your code and try found why you get this error. I use cocos2d-x version 3.17.

**Comment by drelaptop** [comment]
> In our case it was caused by a sdkbox callback sent on a different thread than we expected.

refer the discuss at  https://github.com/cocos2d/cocos2d-x/issues/19077#issuecomment-426510974 , it may a thread issues

**Comment by tamngonesv030** [comment]
I same that problem on IOS version 13.4.1. 
How i can fix it?
