### ISSUE TITLE
New Audio Engine Freezes game on android 5.0.2

### ISSUE THREAD

**Issue by algenepulido** [cocos2d/cocos2d-x#12479]
I have a game for ios and android. The new audio engine works well on ios but has a bug on android. I tested on android 5.0.2. To replicate the bug, quickly stop then play, stop then play, stop then play the same audio file all over again and again... In ios it's fine... The following is the log on android.

E/libOpenSLES(28903): frameworks/wilhelm/src/android/AudioPlayer_to_android.cpp:779: pthread_mutex_lock_timeout_np returned 110
E/libOpenSLES(28903): frameworks/wilhelm/src/android/AudioPlayer_to_android.cpp:779: pthread_mutex_lock_timeout_np returned 110
E/libOpenSLES(28903): frameworks/wilhelm/src/android/AudioPlayer_to_android.cpp:779: pthread_mutex_lock_timeout_np returned 110
E/libOpenSLES(28903): frameworks/wilhelm/src/android/AudioPlayer_to_android.cpp:779: pthread_mutex_lock_timeout_np returned 110
E/libOpenSLES(28903): frameworks/wilhelm/src/android/AudioPlayer_to_android.cpp:779: pthread_mutex_lock_timeout_np returned 110
E/libOpenSLES(28903): frameworks/wilhelm/src/android/AudioPlayer_to_android.cpp:779: pthread_mutex_lock_timeout_np returned 110
W/libOpenSLES(28903): frameworks/wilhelm/src/android/AudioPlayer_to_android.cpp:779: pthread 0xa1d33000 (tid 3931) sees object 0xaf65d600 was locked by pthread 0xb3d18000 (tid 2971) at frameworks/wilhelm/src/itf/IObject.c:411

Thanks for the help!
ginealgames

**Comment by WenhaiLin** [comment]
Duplicated with: https://github.com/cocos2d/cocos2d-x/issues/11466
Fixed at https://github.com/cocos2d/cocos2d-x/pull/11762

**Comment by KenRogoway** [comment]
Same issue exists in Cocos2d-x 2.2.6.  Do you have a potential fix for that too?

**Comment by Jayatubi** [comment]
@WenhaiLin This issue still exists in Cocos2dx 2.2.6. Could you please provide a fix?

**Comment by DonMizzi** [comment]
Some news for Cocos 2.2.6?
Someone have done the fix?
Thank you
