### ISSUE TITLE
Issues with new scenes.

### ISSUE THREAD

**Issue by eliodecolli** [cocos2d/cocos2d-x#13094]
So here's the deal:
1. I create a new scene and fetch inside it a layer with additional sprites and events.
2. One of these sprites has a physics body.
3. That precise sprite (with a physics body) doesn't appear in the scene when running the game, when I try to change its position (with a mouse event) it then appears.
4. Contact between that sprite and additional bullets sprites doesn't trigger any callback. (Bitmasks and category and testconactbitmask are all set up properly).
However all of these happens only when I create a new custom scene, if I edit directly the built-in "HelloWorld" scene then everything is alright (well, expect for physical contact callbacks which don't happen whatsoever).

Thing is, this is really starting to become annoying as I cannot continue with further projects unless I finish this one.

**Comment by eliodecolli** [comment]
The bug seems to be fixed, however I did manage to fix it by simply fetching everything in a layer, removing the initial layer (created by HelloWorld) and replacing it with the new layer containing the "scene".
This is not really a fix as I am not wishing to keep everything in the same scene and only changing layers of that scene it is not what I am trying to achieve and is a great loss.

**Comment by zilongshanren** [comment]
@ItsElioBaby 
So your problem was fixed, right?

**Comment by eliodecolli** [comment]
No, I simply managed to bypass it by replacing the layer, I still cannot replace scenes which contains physics bodies as they do not appear inside the scene.
I've also posted this http://discuss.cocos2d-x.org/t/issues-with-scenes-physicsjointfixed/22957 in the forums concerning about a new issue. I'm having a really bad time with this framework tbh
