### ISSUE TITLE
ios 9 opengl error

### ISSUE THREAD

**Issue by kakamatong** [cocos2d/cocos2d-x#14276]
When I cut back my game from an application，opengl take a error 
![20151030203314](https://cloud.githubusercontent.com/assets/12620172/10845910/adcdb64e-7f46-11e5-9277-f5df0c87ec0c.jpg)

**Comment by kakamatong** [comment]
OpenGL error 0x0506 in -[CCEAGLView swapBuffers] 324

**Comment by kakamatong** [comment]
use cocos2dx 3.3

**Comment by ondesly** [comment]
Found the same issue on cocos2dx 3.8. I am just hiding the app by central button. It happens only if I use Launch Screen File.

failed to call context
cocos2d: surface size: 0x0
Failed to make complete framebuffer object 0x8CD6

OpenGL error 0x0506 in cocos/renderer/CCFrameBuffer.cpp applyFBO 444

FrameBuffer Status Error 36054
OpenGL error 0x0506 in cocos/renderer/CCFrameBuffer.cpp applyFBO 444

FrameBuffer Status Error 36054
FrameBuffer Status Error 36054
OpenGL error 0x0506 in cocos/renderer/CCRenderer.cpp saveRenderState 161

OpenGL error 0x0506 in cocos/renderer/CCRenderer.cpp restoreRenderState 192

FrameBuffer Status Error 36054
OpenGL error 0x0502 in -[CCEAGLView swapBuffers] 324

**Comment by gestern** [comment]
**The issue is still exists at cocos2dx 3.10**

**Comment by slackmoehrle** [comment]
any idea on how to reproduce this?

**Comment by gestern** [comment]
> any idea on how to reproduce this?

You have to specify "Launch Screen File" in your cocos2d-x project in xCode

**Comment by xiongdi9456** [comment]
The issue still exists at cocos2d-x 3.11

**Comment by unexpect3rd** [comment]
I am on 3.10.
I called [[UIApplication sharedApplication] openURL:url] to open a website, and when returning to the app using the top left iOS quick return link, this happens.

And after some testing I noticed, for me, it happens when the above actions are performed and SDKBox::PluginAdmob::cache() is being called in AppDelegate::applicationWillEnterForeground().

**Comment by minggo** [comment]
@xiongdi9456 how can i reproduce it?

**Comment by davidejones88** [comment]
Hello,
I'm facing a similar issue with 3.12

When I put the device to sleep mode (iphone5, sleep mode induced by tapping the hardware button on top of the device, NOT the home button) this is the log I get in xCode:

```
2016-08-12 11:42:28.777 ShapeHLC-mobile[2503:778237] failed to call context
2016-08-12 11:42:28.778 ShapeHLC-mobile[2503:778237] cocos2d: surface size: 0x0
2016-08-12 11:42:28.778 ShapeHLC-mobile[2503:778237] Failed to make complete framebuffer object 0x8CD6
OpenGL error 0x0506 in /Users/davide/Desktop/cocos2d-x-3.12/projectsColto/ShapeHLC/cocos2d/cocos/renderer/CCFrameBuffer.cpp applyFBO 448
```

When I reopen the app from sleep mode (Slide to unlock the phone etc) this is the xCode log:

```
FrameBuffer Status Error 36054
OpenGL error 0x0506 in /Users/davide/Desktop/cocos2d-x-3.12/projectsColto/ShapeHLC/cocos2d/cocos/renderer/CCRenderer.cpp saveRenderState 158

OpenGL error 0x0506 in /Users/davide/Desktop/cocos2d-x-3.12/projectsColto/ShapeHLC/cocos2d/cocos/renderer/CCRenderer.cpp restoreRenderState 188

OpenGL error 0x0506 in /Users/davide/Desktop/cocos2d-x-3.12/projectsColto/ShapeHLC/cocos2d/cocos/renderer/CCRenderer.cpp saveRenderState 158

OpenGL error 0x0506 in /Users/davide/Desktop/cocos2d-x-3.12/projectsColto/ShapeHLC/cocos2d/cocos/renderer/CCRenderer.cpp restoreRenderState 188

OpenGL error 0x0506 in -[CCEAGLView swapBuffers] 327
OpenGL error 0x0506 in /Users/davide/Desktop/cocos2d-x-3.12/projectsColto/ShapeHLC/cocos2d/cocos/renderer/CCFrameBuffer.cpp applyFBO 448
```

And the log loops endlessly.
On screen EVERYTHING is frozen, but I can actually play the game in the background, touches and audio works, but openGL simply doesn't display the frame buffer on the screen. 

IMPORTANT NOTE: I'm using the Facebook SDK (not SDKBOX, but directly from facebook dev website) and I've noticed that if I comment this line

`[FBSDKAppEvents activateApp];`

in applicationDidBecomeActive, everything works fine, but as soon as I enable it, I have the issue.

Maybe this might help you debugging the issue!

**Comment by minggo** [comment]
@ricardoquesada do you have any idea? It seems it is something about OpenGL ES context conflict.

**Comment by davidejones88** [comment]
yesterday I tried to fix it buy wrapping 

`- (void) layoutSubviews`

in CCEAGLView-ios.mm

with this code

```
    if(tryVariable == true)
    {
        return;
    }
    tryVariable = true;
```

Basically, if I execute the layoutSubviews just ONCE, it seems to fix the problem. I found the fix in this thread http://stackoverflow.com/questions/9120090/cocos2d-fails-on-ipad-yet-works-in-simulator (the accepted answer), but I'm not sure if this causes other issues (it hasn't so far)

**Comment by ondesly** [comment]
DisplayLinkDirector has variable _invalid and I added method to get it from Director and add these lines in CCEAGLView-ios.mm:

```
- (void) layoutSubviews
{
    if (cocos2d::Director::getInstance()->isInvalid())
    {
        return;
    }

```

It fixed the issue.

**Comment by ricardoquesada** [comment]
I tried to reproduce the issue, but I couldn't :(
But the patch sent by @ondesly makes sense. So I applied it.
I also removed the `DisplayLinkDirector` since it was something inherited from cocos2d-iphone that doesn't make sense on cocos2d-x.

**Comment by ricardoquesada** [comment]
fixed.

**Comment by flybird** [comment]
I find if I add
if (!cocos2d::Director::getInstance()->isValid())
{
   return;
}
My iphone 4 (not 4s) will see a black screen. :P
I use cocos2dx v3.13

**Comment by dzpt** [comment]
still having this trouble in 3.13

**Comment by minggo** [comment]
It is fixed in v3.14, or you should follow the PR above to fix the issue.

**Comment by dzpt** [comment]
@minggo I've followed the instruction of @ondesly , seeing those lines have been added, but still having this error.  `OpenGL error 0x0502 in /CCRenderer.cpp restoreRenderState 188`
The latest stable version is 3.13.1 , can't see 3.14

**Comment by minggo** [comment]
You should follow @ricardoquesada 's commit: https://github.com/cocos2d/cocos2d-x/commit/3ecaa7194438d4a5cbd01bd740e474fae80b19f3.

**Comment by dzpt** [comment]
@minggo I've checked my code and it looks exactly the same as @ricardoquesada commit and still having error.  I'm using the glow effect here http://qiita.com/isaoeka/items/dee8159e2a0c2a37a662

**Comment by minggo** [comment]
What happen if you remove the glow effect?
Does it only happen on iOS 9?
Could you please provide a test case to reproduce it?
Thanks.

**Comment by ondesly** [comment]
@Tom29 How much is fps in your game? I found that if fps is lower then 60, you can get this issue even with the patch.

**Comment by dzpt** [comment]
@ondesly 60fps @minggo  you can try my code here: https://github.com/Tom29/ShaderExample , run with cocos 3.13.1.

**Comment by cwasp** [comment]
Fails on iOS 6, because layoutSubviews called only once, when cocos2d::Director::getInstance()->isValid() return false, so  [renderer_ resizeFromLayer:(CAEAGLLayer*)self.layer]; is never called.
- (void) layoutSubviews
  {
  -    if (!cocos2d::Director::getInstance()->isValid())
  -    {
  -        return;
  -    }
  -   
    [renderer_ resizeFromLayer:(CAEAGLLayer*)self.layer];
    size_ = [renderer_ backingSize];
