### ISSUE TITLE
Ubuntu 16.04 - isnan error

### ISSUE THREAD

**Issue by slackmoehrle** [cocos2d/cocos2d-x#15691]
Ubuntu 16.04. Cocos2d-x v3.11.

Compiling `cpp-tests` results in an error when compiling spidermonkey/js bindings.

![screen shot 2016-05-20 at 1 14 45 pm](https://cloud.githubusercontent.com/assets/7491758/15435889/f1aff242-1e8c-11e6-8b95-368ef4faec6b.png)

Please see this thread on the forums: http://discuss.cocos2d-x.org/t/building-on-ubuntu-16-04-issues/29051

One user suggested adding `using namespace std;` to a few files. After doing this`cpp-tests` still does not compile successfully for me.

**Comment by minggo** [comment]
I think it is fixed with latest codes.

**Comment by minggo** [comment]
@slackmoehrle will you please test with latest codes?

**Comment by slackmoehrle** [comment]
@minggo ok, sure. Happy to test.

**Comment by slackmoehrle** [comment]
so I updated v3-branch, submodule update, download-deps.py

cleaned, cmake, make, etc, still fails.

![screen shot 2016-05-27 at 1 14 12 pm](https://cloud.githubusercontent.com/assets/7491758/15615551/07e91400-240d-11e6-9084-956bdb2d4a24.png)

**Comment by minggo** [comment]
I modified binding generator in #15687 to fix the bug, but because there is not codes to trigger generating new binding codes, so `jsb_cocos2dx_auto.app` is not changed. I will generate the binding codes manually.

**Comment by minggo** [comment]
It is fixed in #15754 and #15753

**Comment by slackmoehrle** [comment]
I'll test again!

**Comment by minggo** [comment]
I think you can sync to latest code to test.

**Comment by slackmoehrle** [comment]
@minggo 

it works for `cpp-tests`:
![screen shot 2016-05-31 at 2 54 07 pm](https://cloud.githubusercontent.com/assets/7491758/15686971/7521dd46-2740-11e6-9ad4-08a46e2e629b.png)

and `cocos new ...` too:
![screen shot 2016-05-31 at 3 47 33 pm](https://cloud.githubusercontent.com/assets/7491758/15688245/0ba6b6fa-2747-11e6-8373-bf518ad48403.png)

The only issue I ran into is the well documented **fmod** issue:
https://github.com/cocos2d/cocos2d-x/issues/14961

**Comment by minggo** [comment]
@slackmoehrle yep, i know it. So i close this one since the compiling issue is fixed.

**Comment by uxdxdev** [comment]
I'm getting this issue with 3.11 (.zip) on 16.04 for both cpp-tests and cocos new. Any tips?

EDIT: 

Manually applied fixes from #15754, still fails. 
Did not apply fixes from #15753 so now Im just going to pull the repo and use that.

**Comment by slackmoehrle** [comment]
if you apply both of those fixes you should be all set.

**Comment by uxdxdev** [comment]
@slackmoehrle Got it working now, kind of, Im struggling with the libfmod.so.6 linker error :/ tried cp'ing the files and create sym links but still no go.

**Comment by slackmoehrle** [comment]
hmm, it worked for me once I cp'd the files. If you post your commands and any output, we can have a look.

**Comment by uxdxdev** [comment]
It wouldnt work for me just cp'ing the file and creating symlink but creating the /etc/ld.conf.d/cocos.conf file and adding in the */prebuilt/64-bit/ directory worked fine.
