### ISSUE TITLE
NDK 12

### ISSUE THREAD

**Issue by ryancerium** [cocos2d/cocos2d-x#15713]
The new NDK that Android Studio downloads by default adds the `arm64-v8a` support that https://github.com/cocos2d/cocos2d-x/issues/15566 is looking for, but it doesn't appear to work.

```
Android NDK: ERROR:/home/rphelps/code/proj.android-studio/../cocos2d/external/freetype2/prebuilt/android/Android.mk:cocos_freetype2_static: LOCAL_SRC_FILES points to a missing file
Android NDK: Check that /home/rphelps/code/proj.android-studio/../cocos2d/external/freetype2/prebuilt/android/arm64-v8a/libfreetype.a exists  or that its path is correct
```

**Comment by minggo** [comment]
@ryancerium i also download new Android Studio version and NDK r12. And i can compile the codes without any problem.

**Comment by matdennoigi** [comment]
I also got it :(

**Comment by dsp1589** [comment]
any update on this guys, am getting the same issue in ubuntu 14.04 - cocos2dx latest version

**Comment by minggo** [comment]
I asked help from google guys, and they replied

```
Based on my communication with NDK engineers, it seems that the linker is trying to relocate against an address that is too far away to be encoded into the relocation.
Typically happens in a huge library. Similar problem you can see in this with different wording for different linkers.
There is also a good description here: https://groups.google.com/forum/#!topic/android-ndk/8w112eP9W3k
And the workaround using ARM mode in Android.mk seems to be just delaying the problem.

The best way proposed from the NDK team to resolve this issue was that you file a bug directly on https://github.com/android-ndk/ndk/issues.
```

So it is a bug of NDK. I will create an issue in NDK github issue system and put a link here. Of course, i will try to delay the error happen.

**Comment by minggo** [comment]
Sorry, i answered in wrong issue.

**Comment by piotrros** [comment]
So, the workaround is to add  --app-abi armeabi

**Comment by minggo** [comment]
I fixed some compiling issues, could you please use latest codes to have a try?

**Comment by graph** [comment]
I still get this error.

**Comment by graph** [comment]
I see this line

```
APP_ABI := armeabi
```

in Application.mk should be

```
APP_ABI := armeabi armeabi-v7a x86 arm64-v8a
```

To compile on all processors. And on the latest stable there is no APP_ABI. If anyone is on latest stable they should try setting APP_ABI to the above and see if it works.

**Comment by matdennoigi** [comment]
@graph That work for me:

`APP_ABI := armeabi armeabi-v7a x86` 

Seem, statble version of CCX still not support x64 arch

**Comment by minggo** [comment]
@matdennoigi arch64 will be supported in v3.13. @graph the default ABI is set to armeabi instead of `armeabi armeabi-v7a x86 arm64-v8a` is because it will slow down the compiling speed. Developers should change it themselves. And you have compiling issue with latest codes(the codes in github)?

**Comment by graph** [comment]
Yes I had issue in latest git. There is a missing `#endif` in one of the curl headers.  this file `./curl/include/android/curl/curlbuild.h` also in the ios one `./curl/include/ios/curl/curlbuild.h`. After I figured out why I couldn't compile with the latest android Ndk(APP_ABI issue), I went back to stable and everything is good. Maybe have a comment above that line of supported archs will be helpful. I was wondering what was supported but didn't see any clear indication. 

Thank you.

**Comment by minggo** [comment]
@graph thanks, i fixed it. What's the error you met? How can i reproduce it?

**Comment by graph** [comment]
At first I had the same error as the original error in this thread. Then I decided to try the latest git build to see if it was fixed there. I followed the [Git user attention](https://github.com/cocos2d/cocos2d-x) instructions and just followed the instructions for `How to start a game` section. And for compiling on android it wouldn't compile because of the missing `#endif`. After finding out APP_ABI is the cause of the original error I reverted everything back to stable and just updated APP_ABI as matdennoigi mentioned. and everything was good after that. 

Using android NDK R12.
cocos2d-x git hash I used: 3d757507280b53c29647ed605659688e870921d2

regarding this line: `cocos run -p android -j 4` I added `--android-studio` like so: `cocos run -p android -j 4 --android-studio` to compile the android studio project instead of the eclipse project. The android studio one was failing I haven't tried the regular android project.

everything should be good now. The next person to stumble upon this will see matdennoigi post about APP_ABI and will get their problem solved :). 

Thank you.

**Comment by xdeop** [comment]
Hi,
The error is still appearing using android NDK R13 with cocos2dx 3.13.1 version.

$ cocos compile -p android --android-studio

Android NDK: ERROR:/Users/xxx/Projects/Cocos2dx/SampleProject/proj.android-studio/../cocos2d/external/freetype2/prebuilt/android/Android.mk:cocos_freetype2_static: LOCAL_SRC_FILES points to a missing file    
Android NDK: Check that /Users/xxx/Projects/Cocos2dx/SampleProject/proj.android-studio/../cocos2d/external/freetype2/prebuilt/android/mips/libfreetype.a exists  or that its path is correct   
/Developer/android-ndk-r13/build/core/prebuilt-library.mk:45: *** Android NDK: Aborting    .  Stop._

Or:
Check that /Users/xxx/Projects/Cocos2dx/SampleProject/proj.android-studio/../cocos2d/external/freetype2/prebuilt/android/x86_64/libfreetype.a exists  or that its path is correct 

The error appears when compiling for:
APP_ABI := mips
APP_ABI := mips64
APP_ABI := x86_64

Any help please?
Thanks.

**Comment by ryanbourneuk** [comment]
@xdeop My issues were caused as when I first download Cocos2dx I didn't clone the git repository for it, and I didn't call `python download-deps.py ` and `git submodule update --init ` on the engine directory. This meant that my external folder didn't have any of the required files and I kept getting that error.

Now the folders are populated correctly, I believe that you may be experiencing issues as those external libraries haven't been built against the architectures you have selected. It'll be worth seeing if it's possible to build against them or not - personally I haven't tried it but it'd be interesting to investigate.

**Comment by princegoyal1987** [comment]
@graph @minggo Just asking if APP_ABI is set to 'armeabi', will it run on all the devices? Or we have to mention all the ABIs to support those devices?

**Comment by graph** [comment]
I don't think armeabi is officially supported anymore by processor manufacturers. I don't know how backwards compatible armv7 is to it. If it's fully backwards compatible then you are in luck and should be fine (except for x86). If you must support it then perhaps also do the armv7 compilation too. I would only compile for 1 arch that is specific to the device I'm testing on, to speed up compilation time. then do armv7 & x86, and their 64bit archs for production build. If you know you must have armeabi then add that in too, and obviously it will be must more extra work to support as it's very old and barely any devices these days have it.

**Comment by minggo** [comment]
@princegoyal1987 @graph as i know `armeabi` will support all devices except x86 architecture.

**Comment by princegoyal1987** [comment]
@graph @minggo Thanks for the help.
Just to inform others, I have launched the app with APP_ABI = armeabi, and seems like it supports all the devices except x86. armv7 and later versions seem to be compatible with armeabi.
