### ISSUE TITLE
LNK1181 error when compiling in Release mode

### ISSUE THREAD

**Issue by ArchDelta** [cocos2d/cocos2d-x#16393]
- cocos2d-x version: v3.12
- developing environments
  - VS version: 2015

When I am building game in Release mode using Visual Studio 2015, this error pops out :
LINK : fatal error LNK1181: cannot open input file 'libcurl_imp.lib'

No issues when building in debug mode.

Please assist, thanks.

**Comment by kifcaliph** [comment]
- cocos2d-x version: v3.12

I'd like to add it

**Comment by bsy6766** [comment]
I'm getting same error on latest build (3.14.1). Only happens on Release mode. I'm using Windows 10, VS2015, and running win32 project. 

I also tested with cpp-test and both debug and release mode seem to work without issue.

I think there is an issue with naming with libcurl.lib in 3.14.1 win32 projects.
My old project(3.14) has 'libcurl_imp.lib' in external folder, but my new project(3.14.1) has 'libcurl.lib'. They both uses 'libcurl_imp.lib' (according to Property>Linker>input).

**Comment by dumganhar** [comment]
I tested it on v3 branch and couldn't reproduce this issue.
So it was fixed in the latest v3 branch. I closed this issue.

**Comment by bsy6766** [comment]
I just downloaded github repo again, followed the instruction, double checked, then built the win32 project with release mode (Windows10, VS2015) and I still get the same error. LNK1181 cannot open input file 'libcurl_imp.lib'.

At least, I was able to fix this problem by simply changing 'libcurl.lib' to 'libcur_imp.lib' and run the project.

**Comment by dumganhar** [comment]
@bsy6766 , did you run `python download-deps.py` after pulling the latest code?

**Comment by bsy6766** [comment]
@dumganhar Yes I did (v3-deps-128.zip).

**Comment by dumganhar** [comment]
@bsy6766 , it seems that you're using templates to create new projects.
Yes, some template files were not updated.
I have sent another PR (https://github.com/cocos2d/cocos2d-x/pull/17491) for this issue.
