### ISSUE TITLE
ios10 crash  LayerColor  onDraw 

### ISSUE THREAD

**Issue by jianhuang0** [cocos2d/cocos2d-x#16582]
- cocos2d-x version: cocosdx3.3
- devices test on: ios10
- developing environments
  - NDK version:
  - Xcode version: the last version
  - VS version:
  - brower type and version:

i upgrade my iphone6s's system from ios9 to ios10， game crash frequently on LayerColor  onDraw function glDrawArrays(GL_TRIANGLE_STRIP, 0, 4)

**Comment by ricardoquesada** [comment]
Interesting. Have you tried with cocos2d-x v3.13?

**Comment by wulv1985** [comment]
i guess you are using spine in you app. i met the same problem before, and i found a way to solve:

the following lines in function PolygonBatch::flush is not correct,  it cause the s_attributeFlags in GL:enableVertexAttribs dismatch the real state:

GL::bindVAO(0);
glEnableVertexAttribArray(GLProgram::VERTEX_ATTRIB_POSITION);
glEnableVertexAttribArray(GLProgram::VERTEX_ATTRIB_COLOR);
glEnableVertexAttribArray(GLProgram::VERTEX_ATTRIB_TEX_COORDS);

i solve the crash by replace them by the line below:

GL::enableVertexAttribs(GL::VERTEX_ATTRIB_FLAG_POSITION | GL::VERTEX_ATTRIB_FLAG_COLOR | GL::VERTEX_ATTRIB_FLAG_TEX_COORD);

**Comment by ricardoquesada** [comment]
@wulv1985 where is this `PolygonBatch::flush` function? in which file? I can't find it. Thanks.

**Comment by zengjc1412** [comment]
It seems like to be spine source code in cocos2d-x. 
I found that in this path : cocos/editor-support/spine/PolygonBatch.cpp. In this class it has function PolygonBatch::flush @ricardoquesada. BTW I used cocos2d-x 3.5 (quick) and also meet this problem.

**Comment by ricardoquesada** [comment]
@Zenjc thanks. we replaced that code in v3.12 or (3.11), that's why I can't find it.

**Comment by ricardoquesada** [comment]
BTW, If could some could reproduce this bug in v3.13 would be great.

**Comment by doersa** [comment]
@wulv1985 hi,how can you found this problem was caused by spine's functions...I'm very interesting 
The discovery process.

**Comment by huangbaichao** [comment]
THX, I met the same problem. And I solved with changing codes in spine.

**Comment by jminht** [comment]
@ricardoquesada 
i've solve the problem with the code @wulv1985 told me.
but  i still have some issues.
Could you help me with this?
#16543

**Comment by wulv1985** [comment]
@doersa hi, maybe this will help~
#16543

**Comment by doersa** [comment]
hi,i maybe get it, thanks very much~~

2016-09-20 

doersa 

发件人：wulv1985 notifications@github.com
发送时间：2016-09-20 14:12
主题：Re: [cocos2d/cocos2d-x] ios10 crash LayerColor onDraw (#16582)
收件人："cocos2d/cocos2d-x"cocos2d-x@noreply.github.com
抄送："doersa"doersa@126.com,"Mention"mention@noreply.github.com

@doersa hi, maybe this will help~
#16543

**Comment by minggo** [comment]
@eddie5010 why not send a PR to spine runtime? cocos2d-x can not accept PR that is merged by spine runtime.

**Comment by jasonyuan51** [comment]
@wulv1985 I use your code, and it sloved my problem, it does not crash now,  but another problem comes, all spine objects are transparent, invisible, do you have any idea about this strange problem ? THX

**Comment by wulv1985** [comment]
@jasonyuan51 I haven't met this problem, my cocos version is 3.3, how about you? Is it invisible in all device?

**Comment by yhhwatl** [comment]
@wulv1985 
i've solve the problem with the code.
but I can not understand why ?
Do you explain the situation ?
thank you.

**Comment by wulv1985** [comment]
@yhhwatl hi, maybe this will help
#16543

**Comment by minggo** [comment]
As we updated Spine runtime, and there is not `PolygonBatch.cpp` in Spine runtime, so i close this issue.
