### ISSUE TITLE
Android 7.1 Landscape Screen Orientation Issues

### ISSUE THREAD

**Issue by tapblaze** [cocos2d/cocos2d-x#17171]
- cocos2d-x version: 3.10
- devices test on: Google Pixel, Nexus 6P
- developing environments
   - NDK version: 10e

We have a game that is in landscape mode. The game works fine on Android 4.X, 5.X, 6.X and even 7.0 but for some reason on 7.1 devices it gets confused about the orientation and tries to set itself as portrait which breaks the game's layout and makes it unplayable. We have the following in our android manifest:

`android:screenOrientation="sensorLandscape"
              android:theme="@android:style/Theme.NoTitleBar.Fullscreen"
              android:configChanges="orientation">`

since we want the game to be adapt to either landscape orientations. 

Steps to reproduce

1.) Have device running Android 7.1 in portrait mode
2.) Open the game
3.) Turn device to landscape; game will remain in incorrect orientation

**Comment by tapblaze** [comment]
Is this fixed in cocos2dx 3.14? I see this in the change log: 

`Android: adapt to Android pixel`

However, this orientation issue affects any device running android 7.1

**Comment by SBJoker** [comment]
I used solution from this post:
http://discuss.cocos2d-x.org/t/resolution-problem-while-launching-game-through-push-notification-from-lock-screen/22254/2

**Comment by minggo** [comment]
@tapblaze 3.14 doesn't fix the log. I tried cpp-empty-test on Nexus5x with Android 7.1.1, no error happen.

**Comment by SBJoker** [comment]
First of all, game should run in landscape orientation.

Steps to reproduce:
1. Launch game - everything should be okay at this point.
2. Send game to background, rotate device to portrait orientation
3. Optionally: launch another application in portrait orientation
4. Restore/switch to our game, game screen may rotate again to wrong orientation. (Swap of width and height will occur). 

Hope it will help

**Comment by minggo** [comment]
> Restore/switch to our game, game screen may rotate again to wrong orientation. (Swap of width and height will occur)

Did you mean it will not hundred percent reproduce？

**Comment by SBJoker** [comment]
I mean i don't sure about accurate of steps to reproduce. Because it's from feedback reports from our users. I'm have not device with Android 7.1 to test it by my self. The issue 100% exists.

**Comment by tapblaze** [comment]
Yes, over a dozen players have complained about this and we worked with a few beta testers to confirm that the fix @SBJoker used resolved the issue finally.

**Comment by fresair** [comment]
After using @SBJoker's solution, problem still exit.

**Comment by formatCvt** [comment]
1. You can fix it without changing engine by implementing `applicationScreenSizeChanged()` in your game. Example:
```
/**
@brief  This function will be called when the application screen size is changed.
@param new width
@param new height
*/
void AppDelegate::applicationScreenSizeChanged(int newWidth, int newHeight) {
    if (newWidth > 0 && newHeight > 0) {
        auto director = Director::getInstance();
        auto glview = director->getOpenGLView();
        if (glview) {
            Size frameSize = glview->getFrameSize();
            if (!frameSize.equals(Size(newWidth, newHeight))) {
                // Frame size changed
                glview->setFrameSize(newWidth, newHeight);
                ResolutionPolicy resolutionPolicy = glview->getResolutionPolicy();
                if (resolutionPolicy == ResolutionPolicy::UNKNOWN)
                    resolutionPolicy = ResolutionPolicy::NO_BORDER;
                // Set the design resolution
                glview->setDesignResolutionSize(designResolutionSize.width, designResolutionSize.height, resolutionPolicy);
                // if the frame's height is larger than the height of medium size.
                if (newHeight > mediumResolutionSize.height)
                {
                    director->setContentScaleFactor(MIN(largeResolutionSize.height/designResolutionSize.height, largeResolutionSize.width/designResolutionSize.width));
                }
                // if the frame's height is larger than the height of small size.
                else if (newHeight > smallResolutionSize.height)
                {
                    director->setContentScaleFactor(MIN(mediumResolutionSize.height/designResolutionSize.height, mediumResolutionSize.width/designResolutionSize.width));
                }
                // if the frame's height is smaller than the height of medium size.
                else
                {
                    director->setContentScaleFactor(MIN(smallResolutionSize.height/designResolutionSize.height, smallResolutionSize.width/designResolutionSize.width));
                }
                // Send change orientation event (scenes should change elements position, size etc)
                director->getEventDispatcher()->dispatchCustomEvent("ChangeOrientation");
            }
        }
    }
}
```
2. I can't reproduce this bug on Android 9

**Comment by piotrros** [comment]
This issue is still here. When getting photo from image picker, for example, in onActivityResult I had to add:

```
getGLSurfaceView().postDelayed(new Runnable() {
                            @Override
                            public void run() {
                                setRequestedOrientation(ActivityInfo.SCREEN_ORIENTATION_LANDSCAPE);
                            }
                        }, 1000);
```

This hack forces the app to get to landscape again. It doesn't work if I don't add the delay.

**Comment by drelaptop** [comment]
add a link https://github.com/cocos2d/cocos2d-x/issues/15367 , both are similar
