### ISSUE TITLE
Websocket has not event when off screen disconnect on iOS

### ISSUE THREAD

**Issue by sandfresh** [cocos2d/cocos2d-x#17315]
- cocos2d-x version: 3.13.1
- devices test on: iphone 5
- developing environments
   - NDK version:
   - Xcode version: 8.2.1
   - VS version:
   - browser type and version:

Steps to Reproduce:

1. Turn off iphone screen 
2. Turn on iphone and back to game.
This time actually the websocket has disconnected
,but the websocket didn't send any event.
This time check the websocket status is still connected.

**Comment by mdmivanov** [comment]
I encountered a similar issue but on my side is reproduced only for SSL connection, I think the problem is in internal library crash (libwebsocket) that raise signal SIGPIPE when ssl connection was aborted.

**Comment by dumganhar** [comment]
@mdmivanov , please refer to this issue https://github.com/cocos2d/cocos2d-x/issues/17369

**Comment by PatriceJiang** [comment]
This issue is fixed in the current version. @minggo

**Comment by Kingurus** [comment]
Still happening in version 3.17. It is not the same as the SIGPIPE issue. This is happening only on ios when you have a websocket open (mine is ssl) and your iphone screen goes off/idle, or you click the button for sleep/idle, about 5-7 seconds after the phone screen goes black, the websocket is disconnected and no events are fired. When you bring back the app, the websocket still thinks it is "OPEN" but the connection is dead.  No websocket events even after the phone is active again.  I verified it on the server side, the connection is closed

**Comment by Kingurus** [comment]
Hi again, I think it is a bug so here are the full details. I'm using cocos2d-x 3.17 which includes lws 2.1.0. My app connects with wss to the server. it is working well on android/ios/win32/web. but only on ios (I'm using Xcode 9.2/iphone6 on wifi), when the app becomes inactive (when iphone goes idle or sleep/idle button pressed), wss disconnects silently immediately when screen goes black (5-7 seconds sometimes sooner). No event is fired even when the app is active again. I verified it very well, the server clearly shows it was disconnected but the app still thinks it is connected and last event was "open". I checked cocos WebSocket.cpp wrapper, it does not get any event either, the only thing that happens there is the callbacks related to polling stop. 
App's log shows: nw_socket_get_input_frames recvmsg(fd 19, 1024 bytes): [57] Socket is not connected
Anyone can suggest a work-around?
