### ISSUE TITLE
AudioEngine crash

### ISSUE THREAD

**Issue by semgilo** [cocos2d/cocos2d-x#17494]
- cocos2d-x version:3.14
- devices test on:iPhone 6 
- developing environments

May be it crash when preloading and uncaching the sound At the same time, but i can't produce it always

i received some crashes from test flight 
<img width="803" alt="294aff8a-b1e9-4ee9-9d17-c77f5b914a24" src="https://cloud.githubusercontent.com/assets/7121873/23885646/8964b9ee-08af-11e7-8783-0066db9210f1.png">

the device logs:
```
Thread 6 name:  AURemoteIO::IOThread
Thread 6 Crashed:
0   AudioToolbox                  	0x0000000183a80608 CrashIfClientProvidedBogusAudioBufferList + 156
1   AudioToolbox                  	0x0000000183a80480 AudioConverterConvertComplexBuffer + 300
2   AudioToolbox                  	0x0000000183ae439c AUSpatialMixer::Render(unsigned int&, AudioTimeStamp const&, unsigned int) + 1392
3   AudioToolbox                  	0x0000000183b8a42c AUBase::DoRenderBus(unsigned int&, AudioTimeStamp const&, unsigned int, AUOutputElement*, unsigned int, AudioBufferList&) + 216
4   AudioToolbox                  	0x0000000183b88c34 AUBase::DoRender(unsigned int&, AudioTimeStamp const&, unsigned int, unsigned int, AudioBufferList&) + 604
5   AudioToolbox                  	0x0000000183bb2038 AUMethodRender(void*, unsigned int*, AudioTimeStamp const*, unsigned int, unsigned int, AudioBufferList*) + 44
6   AudioToolbox                  	0x0000000183b8d094 AUInputElement::PullInput(unsigned int&, AudioTimeStamp const&, unsigned int, unsigned int) + 148
7   AudioToolbox                  	0x0000000183b80548 AUInputFormatConverter2::InputProc(OpaqueAudioConverter*, unsigned int*, AudioBufferList*, AudioStreamPacketDescription**, void*) + 216
8   AudioToolbox                  	0x0000000183ad3318 AudioConverterChain::CallInputProc(unsigned int) + 332
9   AudioToolbox                  	0x0000000183ad3000 AudioConverterChain::FillBufferFromInputProc(unsigned int*, CABufferList*) + 148
10  AudioToolbox                  	0x0000000183aaea5c BufferedAudioConverter::GetInputBytes(unsigned int, unsigned int&, CABufferList const*&) + 180
11  AudioToolbox                  	0x0000000183addb58 Resampler2Wrapper::RenderOutput(CABufferList*, unsigned int, unsigned int&) + 196
12  AudioToolbox                  	0x0000000183aae8e4 BufferedAudioConverter::FillBuffer(unsigned int&, AudioBufferList&, AudioStreamPacketDescription*) + 444
13  AudioToolbox                  	0x0000000183ad2d80 AudioConverterChain::RenderOutput(CABufferList*, unsigned int, unsigned int&, AudioStreamPacketDescription*) + 116
14  AudioToolbox                  	0x0000000183aae8e4 BufferedAudioConverter::FillBuffer(unsigned int&, AudioBufferList&, AudioStreamPacketDescription*) + 444
15  AudioToolbox                  	0x0000000183a8793c AudioConverterFillComplexBuffer + 340
16  AudioToolbox                  	0x0000000183b80208 AUInputFormatConverter2::PullAndConvertInput(AudioTimeStamp const&, unsigned int&, AudioBufferList&, AudioStreamPacketDescription*, bool&) + 120
17  AudioToolbox                  	0x0000000183b7fc9c AUConverterBase::RenderBus(unsigned int&, AudioTimeStamp const&, unsigned int, unsigned int) + 268
18  AudioToolbox                  	0x0000000183b8a42c AUBase::DoRenderBus(unsigned int&, AudioTimeStamp const&, unsigned int, AUOutputElement*, unsigned int, AudioBufferList&) + 216
19  AudioToolbox                  	0x0000000183b88c34 AUBase::DoRender(unsigned int&, AudioTimeStamp const&, unsigned int, unsigned int, AudioBufferList&) + 604
20  AudioToolbox                  	0x0000000183b6edb8 AURemoteIO::PerformIO(unsigned int, unsigned int, unsigned int, AudioTimeStamp const&, AudioTimeStamp const&, AudioBufferList const*, AudioBufferList*, int&) + 488
21  AudioToolbox                  	0x0000000183b6fd48 AURIOCallbackReceiver_PerformIO + 560
22  AudioToolbox                  	0x0000000183b6622c _XPerformIO + 104
23  AudioToolbox                  	0x0000000183a93924 mshMIGPerform + 248
24  AudioToolbox                  	0x0000000183b39c30 MSHMIGDispatchMessage + 36
25  AudioToolbox                  	0x0000000183b6f0fc AURemoteIO::IOThread::Run() + 136
26  AudioToolbox                  	0x0000000183b72914 AURemoteIO::IOThread::Entry(void*) + 12
27  AudioToolbox                  	0x0000000183a7ed70 CAPThread::Entry(CAPThread*) + 124
28  libsystem_pthread.dylib       	0x0000000180ef7b28 _pthread_body + 156
29  libsystem_pthread.dylib       	0x0000000180ef7a8c _pthread_body + 0
30  libsystem_pthread.dylib       	0x0000000180ef5028 thread_start + 4
```

**Comment by dumganhar** [comment]
Thanks for your feedback. I could reproduce this issue by the last test case in cpp-tests/NewAudioEngineTest.

![screen shot 2017-03-15 at 09 37 35](https://cloud.githubusercontent.com/assets/493372/23929757/36d5ad5a-0963-11e7-85df-aa637f88f8a1.png)

**Comment by dumganhar** [comment]
Fixed this issue at https://github.com/cocos2d/cocos2d-x/pull/17500.

**Comment by semgilo** [comment]
@dumganhar @minggo
timerWithTimeInterval only available for iOS 10.0 ,when run in iOS 9.0 or other, it will crash
`+ (NSTimer *)timerWithTimeInterval:(NSTimeInterval)interval repeats:(BOOL)repeats block:(void (^)(NSTimer *timer))block API_AVAILABLE(macosx(10.12), ios(10.0), watchos(3.0), tvos(10.0));`
```C++
-        free(_pcmData);
 +        // fixed #17494: CrashIfClientProvidedBogusAudioBufferList
 +        // We're using 'alBufferDataStaticProc' for speeding up
 +        // the performance of playing audio without preload, but we need to manage the memory by ourself carefully.
 +        // It's probably that '_pcmData' is freed before OpenAL finishes the audio render task,
 +        // then 'CrashIfClientProvidedBogusAudioBufferList' may be triggered.
 +        // 'cpp-tests/NewAudioEngineTest/AudioSwitchStateTest' can reproduce this issue without the following fix.
 +        // The workaround is delaying 200ms to free pcm data.
 +        char* data = _pcmData;
 +        NSTimer* timer = [NSTimer timerWithTimeInterval:0.2 repeats:NO block:^(NSTimer* t) {
 +            free(data);
 +        }];
 +
 +        [[NSRunLoop currentRunLoop] addTimer:timer forMode:NSDefaultRunLoopMode];
```

**Comment by shaniamjad** [comment]
I am still getting this crash even after this change. I am using Cocos2dx3.15.1 and i have confirmed that i have the changes of setTimeOut function. 
Any ideas why this still be occurring and how it can be fixed? Thanks
@dumganhar @minggo

**Comment by hazbolaKor** [comment]
I am using cocos2d-x 3.15.1 and still have the same crash log. Do you have any other solution?

**Comment by shaniamjad** [comment]
@dumganhar  @minggo Daily i am getting lots of crashes. Take a look at the Crashlogs.
http://crashes.to/s/2b2b10177a7
Please help to solve these. Thanks

**Comment by guilhemvors** [comment]
@dumganhar @minggo

We are also seeing this error on our side (we are on 3.16):

```
AURemoteIO::IOThread (13): EXC_BAD_ACCESS (code=1, address=0x10ff65000)

Crashed: AURemoteIO::IOThread
0  AudioToolbox                   0x188277908 CrashIfClientProvidedBogusAudioBufferList + 56
1  AudioToolbox                   0x188157088 AudioConverterConvertComplexBuffer + 920
2  AudioToolbox                   0x1881514d8 AUSpatialMixer::Render(unsigned int&, AudioTimeStamp const&, unsigned int) + 1652
3  AudioToolbox                   0x18827d480 AUBase::DoRenderBus(unsigned int&, AudioTimeStamp const&, unsigned int, AUOutputElement*, unsigned int, AudioBufferList&) + 172
4  AudioToolbox                   0x18827cc0c AUBase::DoRender(unsigned int&, AudioTimeStamp const&, unsigned int, unsigned int, AudioBufferList&) + 948
5  AudioToolbox                   0x188285fb0 AUMethodRender(void*, unsigned int*, AudioTimeStamp const*, unsigned int, unsigned int, AudioBufferList*) + 44
6  AudioToolbox                   0x187ffe8c4 AUConverterBase::RenderBus(unsigned int&, AudioTimeStamp const&, unsigned int, unsigned int) + 324
7  AudioToolbox                   0x187ee24ec AURemoteIO::RenderBus(unsigned int&, AudioTimeStamp const&, unsigned int, unsigned int) + 104
8  AudioToolbox                   0x18827d480 AUBase::DoRenderBus(unsigned int&, AudioTimeStamp const&, unsigned int, AUOutputElement*, unsigned int, AudioBufferList&) + 172
9  AudioToolbox                   0x18827cc0c AUBase::DoRender(unsigned int&, AudioTimeStamp const&, unsigned int, unsigned int, AudioBufferList&) + 948
10 AudioToolbox                   0x187ee2198 AURemoteIO::PerformIO(unsigned int, unsigned int, unsigned int, AudioTimeStamp const&, AudioTimeStamp const&, AudioBufferList const*, AudioBufferList*, int&) + 756
11 AudioToolbox                   0x187ee3610 AURIOCallbackReceiver_PerformIO + 356
12 AudioToolbox                   0x188077d98 _XPerformIO + 104
13 AudioToolbox                   0x188264fcc mshMIGPerform + 232
14 AudioToolbox                   0x1882651e4 MSHMIGDispatchMessage + 36
15 AudioToolbox                   0x187ee2930 AURemoteIO::IOThread::Run() + 288
16 AudioToolbox                   0x187ee6eb0 AURemoteIO::IOThread::Entry(void*) + 160
17 AudioToolbox                   0x18826d090 CAPThread::Entry(CAPThread*) + 84
18 libsystem_pthread.dylib        0x1840782b4 _pthread_body + 308
19 libsystem_pthread.dylib        0x184078180 _pthread_body + 310
20 libsystem_pthread.dylib        0x184076b74 thread_start + 4
```

even with the fix

**Comment by guilhemvors** [comment]
@dumganhar @minggo

We are playing lots of sounds at the same time, and what we see is that we get some :

`Fail to play XXX.caf cause by limited max instance of AudioEngine.`

usually everything wokrs fine, but sometimes we get the aforementionned crash.

When it happens, there are a lot of thread waiting:

```
#0	0x00000001867dd150 in __psynch_cvwait ()
#1	0x00000001868f2d30 in _pthread_cond_wait$VARIANT$mp ()
#2	0x0000000185e96ea4 in std::__1::condition_variable::wait(std::__1::unique_lock<std::__1::mutex>&) ()
#3	0x0000000101f551bc in cocos2d::experimental::AudioEngine::AudioEngineThreadPool::threadFunc() at .../cocos2d-x/cocos/audio/AudioEngine.cpp:137
#4	0x0000000101f56be8 in decltype(*(std::__1::forward<cocos2d::experimental::AudioEngine::AudioEngineThreadPool*&>(fp0)).*fp(std::__1::forward<>(fp1))) std::__1::__invoke<void (cocos2d::experimental::AudioEngine::AudioEngineThreadPool::*&)(), cocos2d::experimental::AudioEngine::AudioEngineThreadPool*&, void>(void (cocos2d::experimental::AudioEngine::AudioEngineThreadPool::*&&&)(), cocos2d::experimental::AudioEngine::AudioEngineThreadPool*&&&) [inlined] at /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/type_traits:4232
#5	0x0000000101f56b78 in std::__1::__bind_return<void (cocos2d::experimental::AudioEngine::AudioEngineThreadPool::*)(), std::__1::tuple<cocos2d::experimental::AudioEngine::AudioEngineThreadPool*>, std::__1::tuple<>, __is_valid_bind_return<void (cocos2d::experimental::AudioEngine::AudioEngineThreadPool::*)(), std::__1::tuple<cocos2d::experimental::AudioEngine::AudioEngineThreadPool*>, std::__1::tuple<> >::value>::type std::__1::__apply_functor<void (cocos2d::experimental::AudioEngine::AudioEngineThreadPool::*)(), std::__1::tuple<cocos2d::experimental::AudioEngine::AudioEngineThreadPool*>, 0ul, std::__1::tuple<> >(void (cocos2d::experimental::AudioEngine::AudioEngineThreadPool::*&)(), std::__1::tuple<cocos2d::experimental::AudioEngine::AudioEngineThreadPool*>&, std::__1::__tuple_indices<0ul>, std::__1::tuple<>&&) [inlined] at /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/functional:2214
#6	0x0000000101f56b48 in std::__1::__bind_return<void (cocos2d::experimental::AudioEngine::AudioEngineThreadPool::*)(), std::__1::tuple<cocos2d::experimental::AudioEngine::AudioEngineThreadPool*>, std::__1::tuple<>, __is_valid_bind_return<void (cocos2d::experimental::AudioEngine::AudioEngineThreadPool::*)(), std::__1::tuple<cocos2d::experimental::AudioEngine::AudioEngineThreadPool*>, std::__1::tuple<> >::value>::type std::__1::__bind<void (cocos2d::experimental::AudioEngine::AudioEngineThreadPool::*)(), cocos2d::experimental::AudioEngine::AudioEngineThreadPool*>::operator()<>() [inlined] at /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/functional:2247
#7	0x0000000101f56b28 in decltype(std::__1::forward<std::__1::__bind<void (cocos2d::experimental::AudioEngine::AudioEngineThreadPool::*)(), cocos2d::experimental::AudioEngine::AudioEngineThreadPool*> >(fp)(std::__1::forward<>(fp0))) std::__1::__invoke<std::__1::__bind<void (cocos2d::experimental::AudioEngine::AudioEngineThreadPool::*)(), cocos2d::experimental::AudioEngine::AudioEngineThreadPool*> >(std::__1::__bind<void (cocos2d::experimental::AudioEngine::AudioEngineThreadPool::*)(), cocos2d::experimental::AudioEngine::AudioEngineThreadPool*>&&) [inlined] at /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/type_traits:4291
#8	0x0000000101f56b14 in void std::__1::__thread_execute<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, std::__1::__bind<void (cocos2d::experimental::AudioEngine::AudioEngineThreadPool::*)(), cocos2d::experimental::AudioEngine::AudioEngineThreadPool*> >(std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, std::__1::__bind<void (cocos2d::experimental::AudioEngine::AudioEngineThreadPool::*)(), cocos2d::experimental::AudioEngine::AudioEngineThreadPool*> >&, std::__1::__tuple_indices<>) [inlined] at /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/thread:336
#9	0x0000000101f56af0 in void* std::__1::__thread_proxy<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, std::__1::__bind<void (cocos2d::experimental::AudioEngine::AudioEngineThreadPool::*)(), cocos2d::experimental::AudioEngine::AudioEngineThreadPool*> > >(void*) at /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/thread:346
#10	0x00000001868f031c in _pthread_body ()
#11	0x00000001868f01e8 in _pthread_start ()
#12	0x00000001868eec28 in thread_start ()

```

I don't know if it has an incidence, or if it is a factor for the bug to happen. What it looks like is that the data to play the sound is destroyed before the openal engine starts playing them, and thus tries to access bad memory?

**Comment by guilhemvors** [comment]
looks like other people are reporting this crash on ios:

https://stackoverflow.com/questions/32946766/ios-audiotoolbox-crashes

**Comment by rizwangaminations** [comment]
@dumganhar @minggo
Please help
We are also seeing similar crashes in our app. 
App is using cocos2dx 3.15.1 version.
Crashes are occuring on iOS 8 and 9.

**Crashed: AURemoteIO::IOThread
EXC_BAD_ACCESS KERN_INVALID_ADDRESS 0x000000010d9b2382**
Crashed: AURemoteIO::IOThread
0  AudioToolbox                   0x18633b908 CrashIfClientProvidedBogusAudioBufferList + 56
1  AudioToolbox                   0x18621b088 AudioConverterConvertComplexBuffer + 920
2  AudioToolbox                   0x1862154d8 AUSpatialMixer::Render(unsigned int&, AudioTimeStamp const&, unsigned int) + 1652
3  AudioToolbox                   0x186341480 AUBase::DoRenderBus(unsigned int&, AudioTimeStamp const&, unsigned int, AUOutputElement*, unsigned int, AudioBufferList&) + 172
4  AudioToolbox                   0x186340c0c AUBase::DoRender(unsigned int&, AudioTimeStamp const&, unsigned int, unsigned int, AudioBufferList&) + 948
5  AudioToolbox                   0x186349fb0 AUMethodRender(void*, unsigned int*, AudioTimeStamp const*, unsigned int, unsigned int, AudioBufferList*) + 44
6  AudioToolbox                   0x18633bce4 AUInputElement::PullInput(unsigned int&, AudioTimeStamp const&, unsigned int, unsigned int) + 140
7  AudioToolbox                   0x1860c31b4 AUInputFormatConverter2::InputProc(OpaqueAudioConverter*, unsigned int*, AudioBufferList*, AudioStreamPacketDescription**, void*) + 220
8  AudioToolbox                   0x18602a228 AudioConverterChain::CallInputProc(unsigned int) + 596
9  AudioToolbox                   0x186029eb8 AudioConverterChain::FillBufferFromInputProc(unsigned int*, CABufferList*) + 128
10 AudioToolbox                   0x186005a54 BufferedAudioConverter::GetInputBytes(unsigned int, unsigned int&, CABufferList const*&) + 192
11 AudioToolbox                   0x18626e750 Resampler2Wrapper::RenderOutput(CABufferList*, unsigned int, unsigned int&) + 192
12 AudioToolbox                   0x18602ced0 SampleRateConverter::RenderOutput(CABufferList*, unsigned int, unsigned int&, AudioStreamPacketDescription*) + 48
13 AudioToolbox                   0x1860058e4 BufferedAudioConverter::FillBuffer(unsigned int&, AudioBufferList&, AudioStreamPacketDescription*) + 800
14 AudioToolbox                   0x186029ab0 AudioConverterChain::RenderOutput(CABufferList*, unsigned int, unsigned int&, AudioStreamPacketDescription*) + 120
15 AudioToolbox                   0x1860058e4 BufferedAudioConverter::FillBuffer(unsigned int&, AudioBufferList&, AudioStreamPacketDescription*) + 800
16 AudioToolbox                   0x18621aab0 AudioConverterFillComplexBuffer + 1048
17 AudioToolbox                   0x1860c2a00 AUConverterBase::RenderBus(unsigned int&, AudioTimeStamp const&, unsigned int, unsigned int) + 640
18 AudioToolbox                   0x185fa64ec AURemoteIO::RenderBus(unsigned int&, AudioTimeStamp const&, unsigned int, unsigned int) + 104
19 AudioToolbox                   0x186341480 AUBase::DoRenderBus(unsigned int&, AudioTimeStamp const&, unsigned int, AUOutputElement*, unsigned int, AudioBufferList&) + 172
20 AudioToolbox                   0x186340c0c AUBase::DoRender(unsigned int&, AudioTimeStamp const&, unsigned int, unsigned int, AudioBufferList&) + 948
21 AudioToolbox                   0x185fa6198 AURemoteIO::PerformIO(unsigned int, unsigned int, unsigned int, AudioTimeStamp const&, AudioTimeStamp const&, AudioBufferList const*, AudioBufferList*, int&) + 756
22 AudioToolbox                   0x185fa7610 AURIOCallbackReceiver_PerformIO + 356
23 AudioToolbox                   0x18613bd98 _XPerformIO + 104
24 AudioToolbox                   0x186328fcc mshMIGPerform + 232
25 AudioToolbox                   0x1863291e4 MSHMIGDispatchMessage + 36
26 AudioToolbox                   0x185fa6930 AURemoteIO::IOThread::Run() + 288
27 AudioToolbox                   0x185faaeb0 AURemoteIO::IOThread::Entry(void*) + 160
28 AudioToolbox                   0x186331090 CAPThread::Entry(CAPThread*) + 84
29 libsystem_pthread.dylib        0x18213c2b4 _pthread_body + 308
30 libsystem_pthread.dylib        0x18213c180 _pthread_body + 310
31 libsystem_pthread.dylib        0x18213ab74 thread_start + 4

**Comment by guilhemvors** [comment]
Just ot let you know, I have opened a new bug report for 3.17 with a test case (even after the fix):
https://github.com/cocos2d/cocos2d-x/issues/18948

**Comment by drelaptop** [comment]
you can test bug fix with this PR https://github.com/cocos2d/cocos2d-x/pull/19227 @semgilo @shaniamjad @rizwangaminations

**Comment by guilhemvors** [comment]
I have merged the pull. Will keep you up updated if it comes back.

**Comment by umair6** [comment]
@drelaptop I released one game cocos2d-x 3.17.1 with above fix merged manually. I started getting following crash in my game. Occurrence rate is massive. 
https://github.com/cocos2d/cocos2d-x/issues/18597
@minggo

**Comment by minggo** [comment]
How to reproduce it?
