### ISSUE TITLE
Crash in ContextFactory.createContext(Cocos2dxActivity.java)

### ISSUE THREAD

**Issue by Dauch** [cocos2d/cocos2d-x#18058]
- cocos2d-x version: cur v3 branch
- devices test on: android

It is report to my backstage. It happen in a lot devies. This is my code in ```Cocos2dxActivity.java```
```
    private static class ContextFactory implements GLSurfaceView.EGLContextFactory {

        private static int EGL_CONTEXT_CLIENT_VERSION = 0x3098;

        public EGLContext createContext(
            EGL10 egl, EGLDisplay display, EGLConfig eglConfig) {
            
            int[] attributes = {EGL_CONTEXT_CLIENT_VERSION, 2, EGL10.EGL_NONE };
            EGLContext context = egl.eglCreateContext(
                display, eglConfig, EGL10.EGL_NO_CONTEXT, attributes);

            return context;
        }
        public void destroyContext(EGL10 egl, EGLDisplay display, EGLContext context) {
            egl.eglDestroyContext(display, context);
        }
    }
```
This is one of the crash info.

crash info:
```
#87 GLThread 87
java.lang.IllegalArgumentException

1 com.google.android.gles_jni.EGLImpl._eglCreateContext(Native Method)
--
2 com.google.android.gles_jni.EGLImpl.eglCreateContext(EGLImpl.java:54)
3 org.cocos2dx.lib.Cocos2dxActivity$ContextFactory.createContext(Cocos2dxActivity.java)
4 android.opengl.GLSurfaceView$EglHelper.start(GLSurfaceView.java:1030)
5 android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1401)
6 android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1240)
```
device logcat crash info:
```
07-05 06:17:20.827 1121 1121 D Cocos2dxActivity: model=xiaomi-1s
07-05 06:17:20.827 1121 1121 D Cocos2dxActivity: product=xiaomi
07-05 06:17:20.827 1121 1121 D Cocos2dxActivity: isEmulator=false
```
more logcat crash info:
```

07-05 06:17:20.955 1121 1135 D libEGL : Emulator without GPU support detected. Fallback to software renderer.
07-05 06:17:20.955 1121 1135 D libEGL : loaded /system/lib/egl/libGLES_android.so
07-05 06:17:20.955 1121 1135 E device_policy: Can not select an EGLConfig for rendering.
07-05 06:17:20.955 1121 1135 W dalvikvm: threadid=12: thread exiting with uncaught exception (group=0xa6132908)
```
[the whole complete logcat](https://github.com/cocos2d/cocos2d-x/files/1141609/new.9.txt)

**Comment by minggo** [comment]
Since we don't support creating EGL context 3, so i think we don't have to use custom EGLContextFactory.

**Comment by minggo** [comment]
i sent https://github.com/cocos2d/cocos2d-x/pull/18062 to fix it, could you please have a try?

**Comment by Dauch** [comment]
Thanks. But I don't know how to reproduce this bug, I think your patch should fix the problem. After I apply the patch and still meet this crash info I will reopen it. :)

**Comment by umair6** [comment]
I am still getting this crash in my game. I am using cocos2d-x version 3.15.1

`Fatal Exception: java.lang.IllegalArgumentException
       at com.google.android.gles_jni.EGLImpl._eglCreateContext(EGLImpl.java)
       at com.google.android.gles_jni.EGLImpl.eglCreateContext(EGLImpl.java:54)
       at android.opengl.GLSurfaceView$DefaultContextFactory.createContext(GLSurfaceView.java:771)
       at android.opengl.GLSurfaceView$EglHelper.start(GLSurfaceView.java:1030)
       at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1401)
       at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1240)`

**Comment by drelaptop** [comment]
@umair6 Do you merged the code in #18062 to your 3.15.1 engine? this issue was fixed in 3.16 version, we can get this from ` minggo added this to the 3.16 milestone on Jul 13` above.
