### ISSUE TITLE
Can't compile or deploy on windows

### ISSUE THREAD

**Issue by Bilalmirza** [cocos2d/cocos2d-x#18903]
- cocos2d-x version: v3.17
- devices test on: win32 
- developing environments
 
   - VS version: 2017
 
Steps to Reproduce:

C:\Work\explottens\Explottens>cocos compile -p win32
Building mode: debug
Building...
Required VS version : [2013, 2015, 2017]
running: '"C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\devenv.com" "C:\Work\explottens\Explottens\proj.win32\Explottens.sln" /Build "Debug" /Project "Explottens"'

'C:\Program' is not recognized as an internal or external command,
operable program or batch file.
Error running command, return code: 1.

I'm getting this error. It seems like the spaces are causing the trouble. Is there are fix to this?

**Comment by Bilalmirza** [comment]
@minggo @dumganhar can I get some help please :)

**Comment by drelaptop** [comment]
please open the __sln__ file by visual studio manually, it seems like the build command can't read space. or you can select to put the project into a no space path.

**Comment by Bilalmirza** [comment]
@drelaptop  I can build my project in visual studio manually. But the problem is with the deployment...

this command also fails.... 

cocos deploy -p win32 -m release

**Comment by Bilalmirza** [comment]
is there a good way to publish my app with cocos command?

**Comment by drelaptop** [comment]
did you try put the project into non-space path?  cocos command finally call visual studio to compile the project.

what result do you want to publish? put all resource into one single exe package?

**Comment by Bilalmirza** [comment]
project is already in a non-space path

**Comment by Bilalmirza** [comment]
@drelaptop its that the visual studio stores its files in a ceratin path
'"C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\devenv.com" "C:\Work\explottens\Explottens\proj.win32\Explottens.sln"

**Comment by Bilalmirza** [comment]
I want the same result that cocos deploy command does... I mean the package size etc.

**Comment by Bilalmirza** [comment]
@drelaptop is there a workaround or fix for this?

Thanks

**Comment by man2** [comment]
whoa, this simple space issue can't be resolved yet, I still have problem with it now

**Comment by Bilalmirza** [comment]
this was fixed.try 
$cocos deploy -p win32 -m release

this creates a bin folder with all the required files.

**Comment by man2** [comment]
I still get this error when running cocos run or compile
'C:\Program' is not recognized as an internal or external command,operable program or batch file.

**Comment by Bilalmirza** [comment]
which version of cocos are you using?
