### ISSUE TITLE
ios 13 MPMoviePlayerController issues

### ISSUE THREAD

**Issue by fndppx** [cocos2d/cocos2d-x#20078]
- cocos2d-x version:
- devices test on:
- developing environments
   - NDK version:
   - Xcode version:
   - VS version:
   - browser type and version:

MPMoviePlayerController is no longer available. Use AVPlayerViewController in AVKit. when do fixed?

Steps to Reproduce:

1. 
2.

**Comment by fndppx** [comment]
![image](https://user-images.githubusercontent.com/7971897/64114946-f6d3c780-cdc0-11e9-8d69-ba0fd8765292.png)
'MPMoviePlayerController is no longer available. Use AVPlayerViewController in AVKit.' ， if not fixed , app will crash

**Comment by minggo** [comment]
fixed in https://github.com/cocos2d/cocos2d-x/pull/20085

**Comment by fndppx** [comment]
haha, thank you

**Comment by karim-8** [comment]
still appears in ios 13
![Screen Shot 2020-01-01 at 2 45 56 PM](https://user-images.githubusercontent.com/14840152/71641584-16afc500-2ca7-11ea-8374-fe6143138647.png)

**Comment by minggo** [comment]
It is fixed in latest github codes, what engine version did you use?

**Comment by karim-8** [comment]
@minggo i use Xcode 11.1 but anyway the solution for me was replcing the pod code with AVPlayer Code
