### ISSUE TITLE
CCLabelTTF - sometimes rendering as black boxes on Android

### ISSUE THREAD

**Issue by minggo** [cocos2d/cocos2d-x#8305]
# Note

 This issue is migrated from [here](http://www.cocos2d-x.org/issues/3669). It was created at 2014/01/10 20:00:25 +0000
# Description

From time to time, if I exit my game on Android while text is being displayed with CCLabelTTF, then when I re-enter the game, the text is replaced with black boxes. I’m guessing the texture is getting lost. All other textures are fine though.

Another way to reproduce the issue:
# start game
# launch some activity (such as an interstitial ad)
# close that activity and return to game
# at this point, have CCLabelTTF display some text ==> here the text is just black boxes

Also, here’s a related forum post in which more than one developer have experienced this issue:
http://cocos2d-x.org/forums/6/topics/42500
# Comments
- Sheado added comment:
  Ok,

After tinkering I found the cause of the problem.
I was preparing my CCLabelTTF in applicationWillEnterForeground(). Simply moving the code to a runAction(…callfunc…) fixes the problem.

I don’t know if this is a bug or if the documentation just needs to be updated to warn people that they should schedule the work to be done on resuming the application.
- wollf added comment:
  Problem exists with new Label::createFromTTF. If i create a label label like so:
  `Label::createWithTTF(fontBig,"Example ttf text",TextHAlignment::RIGHT);`
  I hide app to background (pressing HOME button) and when i re-enter it i get "white boxes".
  normal label:
  ![before](http://i.imgur.com/Wia5I54.png)
  after re-entering:
  ![after](http://i.imgur.com/VudTjOd.png)

I think this is caused by not reloading ttfConfig created resources in reloadAllTextures.
This is bad and must be fixed, though i can't deal with this myself :(
Tested Device: Google Nexus 7(2013)
- yaxinhoo added comment:
  @Sheado i got the same , does it fixed?
- WenHai added comment:
  Hi guys,which version of Cocos2d-x are you using?

**Comment by WenhaiLin** [comment]
@minggo Confirmed fixed in v3 branch.We should close this issue.

**Comment by MelonS** [comment]
Confirmed fixed in v3 branch?
@minggo @Dhilan007 How to fix? Let me know commit number.

**Comment by ahmed-belal** [comment]
@minggo @Dhilan007 Can you please let me know the commit number? I need to merge this fix into my application running @ v3.2

**Comment by WenhaiLin** [comment]
Hi all, i fixed this issue at https://github.com/cocos2d/cocos2d-x/pull/7363.​ But some people reported this  issue is not yet resolved. I will  check again ASAP.

**Comment by ahmed-belal** [comment]
@Dhilan007 It appears that it was merged into v3.2 already when I downloaded it, but I get the problem still on 3.2. Any advice?

**Comment by manelizzard** [comment]
Hi all, I'm expecting this issue to in the latest version available in git. Is it supposed to be fixed?

**Comment by WenhaiLin** [comment]
Hi all,I fixed it at https://github.com/cocos2d/cocos2d-x/pull/10162, please test again.

**Comment by rdtr** [comment]
Is there still possibility that a label still be broken when you pop a current scene and go back to a previous scene(if exists), because your newly created events are tied to a scene graph priority?

**Comment by toanpv12345** [comment]
Hi Dhilan007,
This bug still sometime appear on version 3.4. I tested on some diveces LG android 4.1.2, Samsung Galaxy Note 3.
Please fix this bug!

**Comment by rdtr** [comment]
Hi, I have still struggled this issue and today seem to find a possible solution.

In my case, I found this issue remaining only when installing via Android Installer, and doesn't happen when I installed via Eclipse or after once kill the App and re-launch. So I googled for a while and found [this stack overflow thread](http://stackoverflow.com/questions/6356467/activity-stack-ordering-problem-when-launching-application-from-android-app-inst).

Then I experimentally inserted these lines in onCreate() of Cocos2dxActivity.java

``` java
if ((getIntent().getFlags() & Intent.FLAG_ACTIVITY_BROUGHT_TO_FRONT) != 0) {
    finish();
    return;
}
```

and this stops happening. I assume Activity being created redundantly(Android sets that flag when launching via the installer) which causes EGL context being lost although we already stop calling onPause() of GLSurfaceView.
I hope it helps some others facing with the same problem, though it's already closed.

Thank you.

**Comment by toanpv12345** [comment]
Hi redtree1112
Thanks for your help, I tested again on some android devices as LG, SamSung, but these bug still exist.
I hope this bug fixed with version 3.5

Thank you.

**Comment by rdtr** [comment]
I'm sorry to hear that.

Just FYI, I'm using v3.2 and also have put a patch in CCLabel's constructor as follows:

``` CCLabel.cpp
auto purgeTextureListener = EventListenerCustom::create(FontAtlas::EVENT_PURGE_TEXTURES, [this](EventCustom* event){
        if (_fontAtlas && _currentLabelType == LabelType::TTF && event->getUserData() == _fontAtlas)
        {
            Node::removeAllChildrenWithCleanup(true);
            _batchNodes.clear();
            _batchNodes.push_back(this);

            // alignText();

            this->updateFont();
            this->setTTFConfig(_fontConfig);
            this->updateContent();
        }
});
_eventDispatcher->addEventListenerWithSceneGraphPriority(purgeTextureListener, this);
```

This totally refreshes all labels so I know it's not an efficient way but it might be effective for some cases.
Also you should check if you're not using your own custom shaders. Otherwise you should reload your shaders on resuming your application to prevent them from breaking textures.
Although I'm not sure if they are all related to this issue, it's everything I can think up regarding this issue so far.

Thanks.

**Comment by toanpv12345** [comment]
Thank redtree1112,
I'm using v3.4, this bug, cocos team fixed in CCLabel's constructor as follows:

```
auto purgeTextureListener = EventListenerCustom::create(FontAtlas::CMD_PURGE_FONTATLAS, [this](EventCustom* event){
        if (_fontAtlas && _currentLabelType == LabelType::TTF && event->getUserData() == _fontAtlas)
        {
            Node::removeAllChildrenWithCleanup(true);
            _batchNodes.clear();
            _batchNodes.push_back(this);

            if (_fontAtlas)
            {
                FontAtlasCache::releaseFontAtlas(_fontAtlas);
            }
        }
    });
    _eventDispatcher->addEventListenerWithSceneGraphPriority(purgeTextureListener, this);

    auto resetTextureListener = EventListenerCustom::create(FontAtlas::CMD_RESET_FONTATLAS, [this](EventCustom* event){
        if (_fontAtlas && _currentLabelType == LabelType::TTF && event->getUserData() == _fontAtlas)
        {
            _fontAtlas = nullptr;
            this->setTTFConfig(_fontConfig);
        }
    });
    _eventDispatcher->addEventListenerWithSceneGraphPriority(resetTextureListener, this);
```

But some devices still appears this bug. In my case, I edited code above as follow:

```
auto resetTextureListener = EventListenerCustom::create(FontAtlas::CMD_RESET_FONTATLAS, [this](EventCustom* event){
        if (_fontAtlas && _currentLabelType == LabelType::TTF && event->getUserData() == _fontAtlas)
        {
            FontAtlasCache::releaseFontAtlas(_fontAtlas);
            FontAtlasCache::releaseFontAtlas(_fontAtlas);
                _fontAtlas = nullptr;
                this->setTTFConfig(_fontConfig);
                this->updateContent();
        }
    });
    _eventDispatcher->addEventListenerWithSceneGraphPriority(resetTextureListener, this);
```

and it fixed!
Thank redtree1112 very much!

**Comment by rdtr** [comment]
I'm glad to hear that😄

**Comment by naghekyan** [comment]
I have this issue on 3.2 and in my case I don't understand even how to reproduce. So don't have a way to check if it is fixed or not. Sometimes it happens sometimes no. Is there a final fix to this?

**Comment by toanpv12345** [comment]
I'm using 3.4, with this patch that I posted above, it only reduces the frequency appear of this bug, I tested my game: resume more times and sometimes it appear. There is not a final fix to this!

**Comment by rdtr** [comment]
Hmm...it seems we have not found a fundamental solution for this issue yet.
(At least so far I haven't see this happen on our game after I put the patch written above though)

If anyone can indicate a way to still reproduce this issue to cocos2d-x team, they'd re-investigate it I think.

**Comment by tigranminasyan** [comment]
Hi all, first of all thanks for suggestions I have the same issue and this thread saved my time.

In my application (https://play.google.com/store/apps/details?id=com.things76.sugarhunt Version
1.1) I am using TTF font in Text::create(); I am developing with cocos2d-x-3.2 and getting this bug tested on Samsung galaxy S4 and galaxy ace 3. 

to fix the issue I applied patch  fix of @WenhaiLin (at #10162) but still had this issue.
To reproduce
#install app
#Open app from play store "open" button
#Navigate to game play
#Press and hold android hardware home button
#Once list of running apps appears release home button and press again to go android home menu.
#run again application but this time pressing app icon in installed applications (not from google play open).
and texts became boxes, so bug still exist after applying  #10162.

after this I applied suggestion made by @redtree1112 

if ((getIntent().getFlags() & Intent.FLAG_ACTIVITY_BROUGHT_TO_FRONT) != 0) {
    finish();
    return;
}

and after this I couldn't reproduce the issue. (at least with the steps I did before :) )

Thanks in advance.

**Comment by shkatulo** [comment]
Current code in CCLabel's constructor reloads only labels in node hierarchy. If Label have no parent, it won't be reloaded. To fix it I've aloso replaced both "addEventListenerWithSceneGraphPriority(...)" with "addEventListenerWithFixedPriority(...)" in constructor.

**Comment by toanpv12345** [comment]
Hi shkatulo!
Can you show detail your patch?

**Comment by WenhaiLin** [comment]
@shkatulo Why Label have no parent?

**Comment by shkatulo** [comment]
Hi, @toanpv12345 !
In original Label's constructor i've just replaced:

``` C++
_eventDispatcher->addEventListenerWithSceneGraphPriority(purgeTextureListener, this);
```

with

``` C++
_eventDispatcher->addEventListenerWithFixedPriority(purgeTextureListener, 1);
```

and

``` C++
_eventDispatcher->addEventListenerWithSceneGraphPriority(resetTextureListener, this);
```

with

``` C++
_eventDispatcher->addEventListenerWithFixedPriority(resetTextureListener, 1);
```

I think update order is not matter. So it works for me.

**Comment by shkatulo** [comment]
@WenhaiLin I have 3-5 labels loaded from CCBI-file. Every has 10-50 lines of text. These labels are loaded during scene creation. Only one of them can be added to node hierarchy in any moment of time. Other labels are cached in memory to avoid its creation every time I add them to hierarchy.

This is particular case. But i think such labels should be updated too.

**Comment by kirushyk** [comment]
Still face this issue with cocos2d-x v.3.5

**Comment by darkdukey** [comment]
Yes, this still happens.

**Comment by kirushyk** [comment]
Similar problem also present for cocos RenderTexture.

**Comment by Talisca** [comment]
You guys are probably building for API level >= 13. You have to add "screenSize" to android:configChanges of your Activity in your AndroidManifest.xml.
Android itself would handle this otherwise and triggers a new Activity initialization (cocos_android_app_init in logcat) if the screen is turned on again. With the above change, your own app will handle those changes..
See also developer.android.com/guide/topics/manifest/activity-element.html#config

Also, there are more errors than the corrupt labels. On some circumstances I got flashing Lines and Triangles, some Textures wouldn't be shown and music would't be paused. All fixed now.

**Comment by hamburml** [comment]
@kirushyk @shkatulo Could you pls test @Talisca's advice? Thanks!

**Comment by iPruch** [comment]
I faced this issue with Cocos2D-X 3.4 and I needed to change all my labelTTF (or ui::Text) to labelBMFont (or ui::TextBMFont) in order for it to disappear completely.

**The problem:**
It never happened to me on iOS (simulator or real device), it hardly occurred on Android (but it did, in most cases when exiting pressing Home and returning to the app) and it almost always showed up in Windows Phone (that is why I noticed this issue). In Windows Phone a different issue also happened: Instead of boxes, characters displayed well but some of them did not appear (for example, instead of "Hello" it would display "He o" or even "H   "). Then I tried a newer version of Cocos2D-X (3.5) but the bug was still present.

**This is what I did:**
After a lot of research, I never found anyone with the same problem (don't know why this page didn't show up then). Later I read in the Cocos2D-X wiki that LabelTTF (or ui::Text) are slow because any change (size, string, etc.) will force Cocos to redraw the texture, and the same wiki article encouraged to use LabelBMFont (or ui::TextBMFont) instead for efficiency reasons. After a bit of testing of BMFonts on Windows Phone, the results were good and I decided to switch all TTF to BMFonts. For this I had to refactor the project in these ways:
- Create BMF versions of the fonts my app is using, in .fnt file format, with this online and free utility: http://kvazars.com/littera/ and place them in the project's Cocos Studio resources folder.
- As I am using Cocos Studio, I needed to change all my CSD files:
  - Replaced all `ctype="TextObjectData"` with `ctype="TextBMFontObjectData"`
  - Replaced all `<FontResource Type="Normal" Path="myfont.ttf" />` with `<LabelBMFontFile_CNB Type="Normal" Path="myfont.fnt"` (if Type="Default", replace it with "Normal" too, or it will ignore your custom font and will use a default font)
  - As TextBMFont (or LabelBMFont) have a fixed size (the one selected when generating the .fnt file), they don't have a `FontSize` property in CSD files. But I didn't want to loose the font sizes, so I decided to replace the `FontSize=` with `UserData=` and retrieve the user data from code to simulate the font size by scaling (I wrote a helper function to do that). There was a problem with this because Cocos wouldn't read the `UserData` property from CSB files, so I needed to go into Cocos2D-X code and workaround it. As this is very specific and kind of offtopic, if someone is interested in all details on this, ask me with a mention so I get a notification and I'll try to come and explain it.
- Replace all `cocos::ui::Text` with `cocos::ui::TextBMFont` from my C++ classes.
- Refactor some parts of the code where I was modifying some properties of Text not present in TextBMFont such as FontSize.

**Results:**
After all this much work, I got it working in all iOS, Android and Windows Phone without the previous graphical errors (boxes or characters disappearing). I expected it to reduce RAM usage too, but the difference wasn't too much on iOS. However, on Windows Phone it reduced from 50 MB to 35-40 MB.

The problem is that now using labels / ui texts is trickier (using UserData to simulate a FontSize property) and there are some minor problems with the bitmap fonts such as slightly worse kerning (although the tool I mentioned does calculate it, it isn't perfect, or not as good as when using LabelTTF/ui::Text), or I would need to re-generate the .fnt files if I need to add characters to the texture. I also had to support multi-resolution resource paths so that a low-resolution device does not load a huge bitmap font texture, or a high-resolution device does not show blurry texts because of a tiny bitmap font texture.

---

**My question:**
With this much work, I don't know if switching back to TTF is a good idea. Has anyone _completely_ fixed the issues of TTF labels? Thank you in advance!

**Comment by darkdukey** [comment]
Sometimes this happens when updating Label from another thread.

**Comment by WenhaiLin** [comment]
Another thread?

**Comment by WenhaiLin** [comment]
@darkdukey You should update Label in GL thread.

**Comment by Leandros** [comment]
Can be reopened.

Since the 5.0 update for the Galaxy S4, all labels using the default font are black. Labels using a non-default font are crashing the application.

**Comment by fiskercui** [comment]
cocos2d-x 3.6 still the same problem

**Comment by uniharmony** [comment]
You guys can read my comment under this post:
https://github.com/cocos2d/cocos2d-x/issues/9499

In one word, don't use glTexSubImage2D to update font texture.

For cocos2d-x 3.3, just simply making _rendererRecreate ALWAYS true, can fix this problem.
Unfortunately, cocos2d-x 3.4 removes _rendererRecreate flag and always uses glTexSubImage2D to update font texture... So the bug appears more frequently in 3.4 games.

**Comment by wayne5ning** [comment]
The problem still exists on version 3.8.1 jsb.
When it's returned from another activity, e.g. from share, in app purchase, ads, instantly created (on the first frame) label is rendered as a black box. Label created on the next frames is rendered correctly.

### the following is rendered as a black box:

```
function show_label(parent){
    parent.addChild(new cc.LabelTTF("test"));
}
show_label(this);
```

### the following is rendered correclty.

```
setTimeOut(show_label.bind(null, this), 0); 

```

**Comment by hgia1234** [comment]
cocos2d-x 3.8 still have this issue

**Comment by xdeop** [comment]
Same problem with cocos2dx v3.9!! 

Its weird because it only happens when the installation of the release apk is not from adb, but from the device (apk sent by email, added to Downloads folder,...).

How can I fix this critical issue??

![efaded48-5d89-463f-98da-3c602c9403ca](https://cloud.githubusercontent.com/assets/5227950/13045142/03baa1cc-d3d2-11e5-9b88-110af2a80d45.jpeg)

**Comment by pankaj-pp** [comment]
Hi guys,
Any update on this issue?. Its still coming on v3.8.
Although it does not comes when i use setTimeout callback to add a label.

**Comment by xdeop** [comment]
Hi,
Any update to fix this issue?

**Comment by kimnamcham** [comment]
same problem on v3.10 cpp, device is sky a870. Any update to fix this issues?
![render_issues](https://cloud.githubusercontent.com/assets/6441065/13448380/664d654c-e055-11e5-8a38-f13a1e81c86c.jpg)

**Comment by darkdukey** [comment]
If you experience this issue on android, try make sure you're modifying the label in the cocos2d-x thread, a easy way to do that is using following code.

```
cocos2d::Director::getInstance()->getScheduler()->performFunctionInCocosThread([=](){
// put your code here.
}
```

**Comment by kimnamcham** [comment]
> If you experience this issue on android, try make sure you're modifying the label in the cocos2d-x thread, a easy way to do that is using following code.

cocos2d::Director::getInstance()->getScheduler()->performFunctionInCocosThread([=](){
// put your code here.
}

Thanks. I will try it.

**Comment by xdeop** [comment]
Hi,
I think I've found my problem. I've removed: _eventDispatcher->removeAllEventListeners();
I had in my code, and its not occurring anymore now! I don't know why it affected because this instruction was called time before pausing the app.

Thanks!

**Comment by liuhello** [comment]
same problem on v3.10 cpp, device is mi 3 、htc m8 and 红米. happened when i background game and change system language times.

**Comment by liuhello** [comment]
I have fixed it like this code :
void FontAtlas::listenRendererRecreated(EventCustom *event)
{
    if (_fontFreeType)
    {
        //add this code 
        for( auto &item: _atlasTextures)
        {
            item.second->setName(0);
        }
        auto eventDispatcher = Director::getInstance()->getEventDispatcher();
        eventDispatcher->dispatchCustomEvent(CMD_PURGE_FONTATLAS,this);
        eventDispatcher->dispatchCustomEvent(CMD_RESET_FONTATLAS,this);
    }
}

**Comment by pyy07** [comment]
any final solution to this issue?

**Comment by stnguyen** [comment]
any solution to this one? it happens on LWF node as well, not just labels

**Comment by dumganhar** [comment]
@stnguyen, could you make sure that:
1. You didn't set string from non-GL thread?
2. You didn't call EventDispatcher::removeAllEventListeners?

If you didn't do these, please make a demo to reproduce this issue.

**Comment by takesoon** [comment]
I have used a violence method to fix this question
in FontAtlasCache.cpp addMethod

```

bool FontAtlasCache::forceReleaseFontAtlas(FontAtlas *atlas)
{
	if (nullptr != atlas)
	{
		for (auto &item : _atlasMap)
		{
			if (item.second && item.second == atlas)
			{
				_atlasMap.erase(item.first);
				delete atlas;
				atlas = nullptr;
				return true;
			}
		}
	}

	return false;
}
```
in FontAtlas::listenRendererRecreated 
```
void FontAtlas::listenRendererRecreated(EventCustom *event)
{
    FontFreeType* fontTTf = dynamic_cast<FontFreeType*>(_font);
    if (fontTTf)
    {
        auto eventDispatcher = Director::getInstance()->getEventDispatcher();
        eventDispatcher->dispatchCustomEvent(CMD_PURGE_FONTATLAS,this);
	FontAtlasCache::forceReleaseFontAtlas(this);
        eventDispatcher->dispatchCustomEvent(CMD_RESET_FONTATLAS,this);
    }
}
```
the reason of the block is fontAtlas sometimes can not be release,but i can't find how it happend

**Comment by germinolegrand** [comment]
Any news on that ?
I get the white boxes 95% of the time on Label ...
@takesoon "violence" solution does not work

**Comment by minggo** [comment]
@germinolegrand could you please create a new issue and describe it in detail? It is better to provide steps to reproduce it.

**Comment by stnguyen** [comment]
for me I just need to put the game in background mode, rotate device, then reopen the game to get my labels turn to white boxes.

Watching a Unity ads and rotate device will do the same thing

**Comment by stnguyen** [comment]
@minggo @dumganhar is there an update to this issue?

**Comment by minggo** [comment]
@stnguyen what's your engine version? Any test case to reproduce it?

**Comment by Swipes13** [comment]
in 3.14 same problem.
To reproduce: android after ad-reward video (hide & open again cocos activity)
in details: IronSource integration, after video some labels in game is just colour boxes

**Comment by stnguyen** [comment]
@minggo same as what @Swipes13 described.
Basically it happens after:

1. App is put on background mode (either by pressing home button or by watching an ads)
AND
2. In background mode, change device orientation (or ad was played in another orientation compared to game)

**Comment by Kotaiba** [comment]
![screenshot_20170911-133626](https://user-images.githubusercontent.com/3635272/30270798-a0e9b918-96f6-11e7-8c68-f49f52b21c10.png)
@minggo  i got the same problem ,using cocos2d-x 3.15.1 . happen on android devices .i use sdkbox gps online when the matach started after finding players 80% of the label turn to white boxes . anyway i can fix it

**Comment by minggo** [comment]
@Kotaiba how did you fix it?

**Comment by Kotaiba** [comment]
@minggo  I did't ,Im asking for a fix :)

**Comment by Kotaiba** [comment]
@minggo After a lot of test ,i think enableOutline(Color4B(0, 0, 0, 255), 3); 90% of the time got the bug ,after stoping enableOutline the bug was 90% less.

**Comment by Kotaiba** [comment]
@mingoo is there will be a fix  for this bug  ?

**Comment by minggo** [comment]
The issue is that we can not reproduce it.

**Comment by Kotaiba** [comment]
@minggo I've fix it ,i delay any label creation or update after any other popup showing like ads ,google online matching and the bug gone , So we should not create label right after ads finish .

**Comment by takesoon** [comment]
@minggo I can reproduce it， in AndroidManifest.xml  set   Anandroid:screenOrientation="unspecified"  ，android:configChanges="locale" ， 关掉手机的方向锁定，然后就让游戏横向和纵向切换，很容易就看出白块了， 这样比较容易复现 虽然大多数游戏不会支持横向和纵向切换，但是会偶尔重新创建activity， 我并不清楚什么情况下会重建，但确实是这样

**Comment by takesoon** [comment]
我按照新版本的方式     FontFreeType* fontTTf = dynamic_cast<FontFreeType*>(_font);
    if (fontTTf)
    {
		relaseTextures();
		_currentPage = 0;
		_currentPageOrigX = 0;
		_currentPageOrigY = 0;
        auto eventDispatcher = Director::getInstance()->getEventDispatcher();
        eventDispatcher->dispatchCustomEvent(CMD_PURGE_FONTATLAS,this);
        eventDispatcher->dispatchCustomEvent(CMD_RESET_FONTATLAS,this);
    } ，这样来改，这个做法给我带来了很多Texture的Crash

**Comment by danlee2025** [comment]
I have encountered this problem too in iOS. Be sure that you should call any update UI things in main queue if you are in mobile environment.

**Comment by bouchard-industries** [comment]
This issue seems to happen if you quickly create Labels after a unity ads shows up. This does not seem to have been fixed yet. Like @Kotaiba said, I can confirm that delaying the creation of Labels worked. Not the final solution but one solution in the meantime.

Temp fix example

In init: scheduleOnce(schedule_selector(Menu::SetupUi), 0.1f); //Delay the font creation.

void Menu::SetupUi(float unused)
{
    //create Label here
}

**Comment by xiaokis** [comment]
@minggo did you fixed this bug？the problem is so common in lg and sansamg phones

**Comment by daniaDlbani** [comment]
I'm having the same issue in **cocos2dx 2.2.6**. Is there any suggestion for that?

**Comment by minggo** [comment]
May be we should fix it like: https://discuss.cocos2d-x.org/t/restart-application-instead-of-reload-all-resources-when-opengl-es-context-lost-on-android/45074
