### ISSUE TITLE
cocos console cannot generate cpp projects from template

### ISSUE THREAD

**Issue by stammen** [cocos2d/cocos2d-x#9293]
The most recent version of cocos console in the v3 branch cannot generate a project using the cpp template. My computer is using Windows 8.1

```
C:\Users\Dale\Documents\GitHub\cocos2d-x-v3-universal>cocos new foo -p com.foo.bar -l cpp -d projects
Running command: new
Traceback (most recent call last):
  File "C:\Users\Dale\Documents\GitHub\cocos2d-x-v3-universal\tools\cocos2d-console\bin\/cocos.py", line 743, in <module>
    run_plugin(command, argv, plugins)
  File "C:\Users\Dale\Documents\GitHub\cocos2d-x-v3-universal\tools\cocos2d-console\bin\/cocos.py", line 706, in run_plugin
    plugin.run(argv, dependencies_objects)
  File "C:\Users\Dale\Documents\GitHub\cocos2d-x-v3-universal\tools\cocos2d-console\plugins\project_new\project_new.py", line 206, in run
    self.parse_args(argv)
  File "C:\Users\Dale\Documents\GitHub\cocos2d-x-v3-universal\tools\cocos2d-console\plugins\project_new\project_new.py", line 135, in parse_args
    self.init(args)
  File "C:\Users\Dale\Documents\GitHub\cocos2d-x-v3-universal\tools\cocos2d-console\plugins\project_new\project_new.py", line 76, in init
    args.language, self._templates_paths, args.template)
  File "C:\Users\Dale\Documents\GitHub\cocos2d-x-v3-universal\tools\cocos2d-console\plugins\project_new\project_new.py", line 240, in __init__
    self._scan()
  File "C:\Users\Dale\Documents\GitHub\cocos2d-x-v3-universal\tools\cocos2d-console\plugins\project_new\project_new.py", line 259, in _scan
    dirs = [name for name in os.listdir(templates_dir) if os.path.isdir(
WindowsError: [Error 5] Access is denied: 'C:\\Users\\Dale\\templates/*.*'
C:\Users\Dale\Documents\GitHub\cocos2d-x-v3-universal>
```

**Comment by ricardoquesada** [comment]
fixed. thanks.

```
C:\Users\Ricardo\tmp>cocos new -lcpp -pcom.foo.bar -dhellodir test
Running command: new
> Copy template into C:\Users\Ricardo\tmp\hellodir\test
> Copying cocos2d-x files...
> Rename project name from 'HelloCpp' to 'test'
> Replace the project name from 'HelloCpp' to 'test'
> Replace the project package name from 'org.cocos2dx.hellocpp' to 'com.foo.bar'
> Replace the mac bundle id from 'org.cocos2dx.hellocpp' to 'com.foo.bar'
> Replace the ios bundle id from 'org.cocos2dx.hellocpp' to 'com.foo.bar'
```

**Comment by stammen** [comment]
- tools/cocos2d-console/bin/cocos new MyGame -p com.your_company.mygame -l cpp -d projects
  Running command: new
  Traceback (most recent call last):
  File "c:/Program Files (x86)/Jenkins/jobs/cocos2d-x-v3/workspace/tools/cocos2d-console/bin/cocos.py", line 740, in <module>
    run_plugin(command, argv, plugins)
  File "c:/Program Files (x86)/Jenkins/jobs/cocos2d-x-v3/workspace/tools/cocos2d-console/bin/cocos.py", line 703, in run_plugin
    plugin.run(argv, dependencies_objects)
  File "c:\Program Files (x86)\Jenkins\jobs\cocos2d-x-v3\workspace\tools\cocos2d-console\plugins\project_new\project_new.py", line 210, in run
    self.parse_args(argv)
  File "c:\Program Files (x86)\Jenkins\jobs\cocos2d-x-v3\workspace\tools\cocos2d-console\plugins\project_new\project_new.py", line 139, in parse_args
    self.init(args)
  File "c:\Program Files (x86)\Jenkins\jobs\cocos2d-x-v3\workspace\tools\cocos2d-console\plugins\project_new\project_new.py", line 80, in init
    self._templates = Templates(args.language, self._templates_paths, args.template)
  File "c:\Program Files (x86)\Jenkins\jobs\cocos2d-x-v3\workspace\tools\cocos2d-console\plugins\project_new\project_new.py", line 244, in __init__
    self._scan()
  File "c:\Program Files (x86)\Jenkins\jobs\cocos2d-x-v3\workspace\tools\cocos2d-console\plugins\project_new\project_new.py", line 263, in _scan
    dirs = [name for name in os.listdir(templates_dir) if os.path.isdir(
  TypeError: coercing to Unicode: need string or buffer, NoneType found
  Build step 'Execute shell' marked build as failure

**Comment by stammen** [comment]
@ricardoquesada  @minggo 

cocos console still does not work. Please reopen the issue

**Comment by dabingnn** [comment]
We have just fixed a cocos console bug in pull request: https://github.com/cocos2d/cocos2d-x/pull/9304
Could you please try it?

**Comment by stammen** [comment]
It works now on my computer and on our Jenkins build computer. Thanks!
